TRUNCATE TABLE country CASCADE;
TRUNCATE TABLE country_group CASCADE;
TRUNCATE TABLE currency CASCADE;
TRUNCATE TABLE organisation CASCADE;
TRUNCATE TABLE language CASCADE;
TRUNCATE TABLE tag CASCADE;
TRUNCATE TABLE tag_category CASCADE;
TRUNCATE TABLE action CASCADE;

TRUNCATE TABLE project CASCADE;
TRUNCATE TABLE event CASCADE;
TRUNCATE TABLE resource CASCADE;
TRUNCATE TABLE policy CASCADE;
TRUNCATE TABLE technology CASCADE;
TRUNCATE TABLE stakeholder CASCADE;
