version: "3"

services:
  database:
    build:
      context: .
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gpml
      POSTGRES_USER: unep
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./sql-init:/docker-entrypoint-initdb.d

