import firstAvatar from "../../images/stakeholder-overview/first-avatar.jpg";
import secondAvatar from "../../images/stakeholder-overview/second-avatar.jpg";
import thirdAvatar from "../../images/stakeholder-overview/third-avatar.png";
export const profiles = [
  {
    about: "Just testing",
    affiliation: 10001,
    country: 1101,
    cv: "image/profile/3",
    email: "example@gmail.com",
    firstName: "Tara",
    geoCoverageType: null,
    geoCoverageValue: null,
    id: 10000,
    idpUsernames: ["google-oauth2|118135033842507285562"],
    lastName: "McLaugh",
    linkedIn: null,
    nonMemberOrganisation: null,
    non_member_organisation: null,
    offering: [311],
    org: {
      geoCoverageType: "global",
      logo: null,
      representativeGroupOther: null,
      secondContact: null,
      subnationalArea: null,
    },
    organisationRole: null,
    photo: firstAvatar,
    publicEmail: false,
    representation: "",
    reviewStatus: "SUBMITTED",
    reviewedAt: null,
    reviewedBy: null,
    role: "USER",
    seeking: [329],
    tags: null,
    title: "Mr",
  },
  {
    about: "Just testing",
    affiliation: 10001,
    country: 288,
    cv: "/cv/profile/1",
    email: "example@gmail.com",
    firstName: "Mediterranean ",
    geoCoverageType: null,
    geoCoverageValue: null,
    id: 10001,
    idpUsernames: ["google-oauth2|118135033842507285562"],
    lastName: "Action Plan (MAP)",
    linkedIn: "example.com",
    nonMemberOrganisation: null,
    non_member_organisation: null,
    offering: [311],
    org: {
      geoCoverageType: "global",
      logo: null,
      representativeGroupOther: null,
      secondContact: null,
      subnationalArea: null,
    },
    organisationRole: null,
    photo: thirdAvatar,
    publicEmail: false,
    representation: "",
    reviewStatus: "SUBMITTED",
    reviewedAt: null,
    reviewedBy: null,
    role: "USER",
    seeking: [329],
    tags: null,
    title: "",
  },
  {
    about: "Just testing",
    affiliation: 10001,
    country: 276,
    cv: "/cv/profile/6",
    email: "example@gmail.com",
    firstName: "John",
    geoCoverageType: null,
    geoCoverageValue: null,
    id: 10002,
    idpUsernames: ["google-oauth2|118135033842507285562"],
    lastName: "Calkovich",
    linkedIn: null,
    nonMemberOrganisation: null,
    non_member_organisation: null,
    offering: [311],
    org: {
      geoCoverageType: "global",
      logo: null,
      representativeGroupOther: null,
      secondContact: null,
      subnationalArea: null,
    },
    organisationRole: null,
    photo: secondAvatar,
    publicEmail: false,
    representation: "",
    reviewStatus: "SUBMITTED",
    reviewedAt: null,
    reviewedBy: null,
    role: "USER",
    seeking: [329],
    tags: null,
    title: "Mr",
  },
];
