import UNEPLogo from "../../images/stakeholder-overview/unep-logo.png";
import TaraAvatar from "../../images/stakeholder-overview/third-avatar.png";
import johnAvatar from "../../images/stakeholder-overview/second-avatar.jpg";

export const suggestedProfiles = [
  {
    role: "USER",
    geo_coverage_values: null,
    tags: [{ 309: "legal services" }, { 327: "legal expert" }],
    email: "",
    first_name: "Tara",
    organisation: [],
    seeking: "legal expert",
    owners: [],
    public_email: false,
    geo_coverage_type: null,
    cv: null,
    affiliation: null,
    lifecycle_phase: [],
    twitter: null,
    linked_in: null,
    sector: [],
    created: "2022-01-18T06:43:26.576464+00:00",
    geo_coverage_country_groups: null,
    modified: "2022-01-24T15:24:31.349154+00:00",
    title: "Ms",
    funding: null,
    representation: "",
    id: 10067,
    picture: TaraAvatar,
    outcome_and_impact: [],
    organisation_role: null,
    url: null,
    focus_area: [],
    last_name: "McLaugh",
    review_status: "APPROVED",
    reviewed_by: 10018,
    currency_amount_invested: [],
    currency_in_kind_contribution: [],
    reviewed_at: "2022-01-24T15:24:31.349154+00:00",
    activity_owner: [],
    geo_coverage_countries: null,
    is_action_being_reported: null,
    country: 404,
    about: "i am happy today",
    activity_term: null,
    offering: "knowledge management",
  },
  {
    geo_coverage_values: ["Western European"],
    organisation: [],
    owners: [],
    geo_coverage_type: "Intergovernmental organization",
    logo: UNEPLogo,
    representative_group_other: null,
    second_contact: null,
    subnational_area: null,
    lifecycle_phase: [],
    name: "Mediterranean Action Plan (MAP)",
    is_member: true,
    sector: [],
    contribution:
      "Reducing levels and impacts of sea-based sources of marine debris including solid waste, lost cargo, abandoned lost or discarded fishing gear, and abandoned vessels introduced into the aquatic environment.;Reduced levels and impacts of (accumulated) marine debris on shorelines, aquatic habitats, and biodiversity.",
    type: "Civil Society (not-for-profit)",
    created: "2021-09-29T11:24:41.854911+00:00",
    representative_group_civil_society: "Non-Governmental Organization (NGOs)",
    representative_group_private_sector: null,
    modified: "2021-09-29T11:24:41.854911+00:00",
    funding: null,
    expertise: null,
    representative_group_government: null,
    id: 337,
    outcome_and_impact: [],
    url: null,
    focus_area: [],
    review_status: "APPROVED",
    reviewed_by: null,
    currency_amount_invested: [],
    currency_in_kind_contribution: [],
    reviewed_at: null,
    activity_owner: [],
    is_action_being_reported: null,
    program:
      "We are concerned with the long-term health of terrestrial and aquatic ecosystems as well as the human activities and natural processes that affect them. We empower people to live sustainably by conveying ecological knowledge and assistance to areas of the world that face environmental challenges. We believe that hunger, poverty, and strife can be alleviated through the wise use of natural resources, coupled with positive economic and social change. ",
    representative_group_academia_research: null,
    created_by: null,
    country: null,
    activity_term: null,
    offering: "knowledge management",
  },
  {
    role: "ADMIN",
    geo_coverage_values: null,
    tags: [{ 311: "software development" }, { 332: "software products" }],
    email: "",
    first_name: "John",
    organisation: [],
    seeking: "marine biologists",
    owners: [],
    public_email: false,
    geo_coverage_type: null,
    cv: null,
    affiliation: {
      geo_coverage_type: "global",
      representative_group_other: null,
      second_contact: null,
      subnational_area: null,
      name: "United Nations Environment Programme (UNEP)",
      is_member: true,
      contribution: null,
      type: "Intergovernmental organization",
      created: "2021-10-29T11:24:41.854911+00:00",
      representative_group_civil_society: null,
      representative_group_private_sector: null,
      modified: "2021-10-29T11:24:41.854911+00:00",
      expertise: null,
      representative_group_government: null,
      id: 1,
      url: "https://www.unep.org/",
      review_status: "APPROVED",
      reviewed_by: null,
      reviewed_at: null,
      program:
        "The United Nations Environment Programme (UNEP) is the leading global environmental authority that sets the global environmental agenda, promotes the coherent implementation of the environmental dimension of sustainable development within the United Nations system, and serves as an authoritative advocate for the global environment. \nOur mission is to provide leadership and encourage partnership in caring for the environment by inspiring, informing, and enabling nations and peoples to improve their quality of life without compromising that of future generations. ",
      representative_group_academia_research: null,
      created_by: null,
      country: 404,
    },
    lifecycle_phase: [],
    twitter: "johncalkovich.com",
    linked_in: "johncalkovich.com",
    sector: [],
    created: "2022-01-18T13:24:39.66919+00:00",
    geo_coverage_country_groups: null,
    modified: "2022-01-24T15:24:46.645097+00:00",
    title: "Mr",
    funding: null,
    representation: "",
    id: 10068,
    picture: johnAvatar,
    outcome_and_impact: [],
    organisation_role: null,
    url: null,
    focus_area: [],
    last_name: " Calkovich",
    review_status: "APPROVED",
    reviewed_by: 10018,
    currency_amount_invested: [],
    currency_in_kind_contribution: [],
    reviewed_at: "2022-01-24T15:24:46.645097+00:00",
    activity_owner: [],
    geo_coverage_countries: null,
    is_action_being_reported: null,
    country: 404,
    about: "None",
    activity_term: null,
    offering: "software development",
  },
];
