apiVersion: apps/v1
kind: Deployment
metadata:
  name: unep-gpml
spec:
  replicas: 1
  selector:
    matchLabels:
        run: unep-gpml
  template:
    metadata:
      labels:
        run: unep-gpml
        unep-gpml-version: "demo"
    spec:
      containers:
      - name: frontend
        image: jmalloc/echo-server:0.1.0
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        resources:
          requests:
            cpu: "100m"
            memory: "32Mi"
          limits:
            cpu: "200m"
            memory: "64Mi"
