apiVersion: batch/v1
kind: Job
metadata:
  name: unep-gpml-fix-stakeholder-roles-${TIMESTAMP}
spec:
  template:
    spec:
      containers:
      - name: unep-gpml-fix-stakeholder-roles
        image: akvo/akvo-clojure-lein:20210124.114043.4437caf
        command: ["/bin/bash", "-c"]
        args:
          - echo Installing git;
            echo "deb http://archive.debian.org/debian buster main" > /etc/apt/sources.list;
            echo "deb http://archive.debian.org/debian-security buster/updates main" >> /etc/apt/sources.list;
            apt-get update && apt-get -qq install -y --no-install-recommends --no-install-suggests git;
            echo Cloning repo;
            git clone https://github.com/akvo/unep-gpml.git;
            cd unep-gpml/backend;
            echo Downloading dependencies with retry;
            for i in {1..3}; do echo "Attempt $i/3"; lein with-profile seeder deps && break || sleep 30; done;
            echo Fixing stakeholder roles;
            lein with-profile seeder run fix-stakeholder-roles
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: unep-gpml
              key: database-url
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/cloudsql/credentials.json"
        volumeMounts:
          - name: unep-gpml-secrets
            mountPath: "/secrets/cloudsql/credentials.json"
            subPath: "cloud-database-service-account.json"
            readOnly: true
      volumes:
        - name: unep-gpml-secrets
          secret:
            secretName: unep-gpml
      restartPolicy: Never
  backoffLimit: 0