DROP TABLE IF EXISTS action_detail CASCADE;
DROP TABLE IF EXISTS action CASCADE;
DROP TABLE IF EXISTS project_action_detail CASCADE;
DROP TABLE IF EXISTS project_action CASCADE;
DROP TABLE IF EXISTS project_country CASCADE;
DROP TABLE IF EXISTS project CASCADE;
