ALTER TABLE organisation DROP COLUMN representative_group_government;
ALTER TABLE organisation DROP COLUMN representative_group_private_sector;
ALTER TABLE organisation DROP COLUMN representative_group_academia_research;
ALTER TABLE organisation DROP COLUMN representative_group_civil_society;
ALTER TABLE organisation DROP COLUMN representative_group_other;
