-- Add transnational country_group_type!
ALTER TABLE country_group DROP CONSTRAINT country_group_name_key;
ALTER TABLE country_group ADD CONSTRAINT country_group_name_type_key UNIQUE(name, type);

insert into country_group(id, name, type) values(121, 'African States', 'transnational');
insert into country_group(id, name, type) values(122, 'Asia-Pacific States', 'transnational');
insert into country_group(id, name, type) values(123, 'Western European', 'transnational');
insert into country_group(id, name, type) values(124, 'Eastern European States', 'transnational');
insert into country_group(id, name, type) values(125, 'Latin American and Caribbean', 'transnational');
insert into country_group(id, name, type) values(126, 'Antarctic', 'transnational');
insert into country_group(id, name, type) values(127, 'Arctic', 'transnational');
insert into country_group(id, name, type) values(128, 'Baltic Sea', 'transnational');
insert into country_group(id, name, type) values(129, 'Black Sea', 'transnational');
insert into country_group(id, name, type) values(130, 'Caspian Sea', 'transnational');
insert into country_group(id, name, type) values(131, 'Western Indian Ocean', 'transnational');
insert into country_group(id, name, type) values(132, 'East Asian Seas', 'transnational');
insert into country_group(id, name, type) values(133, 'Mediterranean', 'transnational');
insert into country_group(id, name, type) values(134, 'North-East Atlantic', 'transnational');
insert into country_group(id, name, type) values(135, 'North West Pacific', 'transnational');
insert into country_group(id, name, type) values(136, 'North East Pacific', 'transnational');
insert into country_group(id, name, type) values(137, 'Pacific Region', 'transnational');
insert into country_group(id, name, type) values(138, 'Red Sea and Gulf of Aden', 'transnational');
insert into country_group(id, name, type) values(139, 'ROPME Sea', 'transnational');
insert into country_group(id, name, type) values(140, 'South Asian Seas', 'transnational');
insert into country_group(id, name, type) values(141, 'South-East Pacific', 'transnational');
insert into country_group(id, name, type) values(142, 'Western Central and Southern Africa', 'transnational');
insert into country_group(id, name, type) values(143, 'Wider Caribbean', 'transnational');
insert into country_group(id, name, type) values(144, 'Basel Convention', 'transnational');
insert into country_group(id, name, type) values(145, 'Rotterdam Convention', 'transnational');
insert into country_group(id, name, type) values(146, 'Stockholm Convention', 'transnational');
insert into country_group(id, name, type) values(147, 'Convention on Climate', 'transnational');
insert into country_group(id, name, type) values(148, 'Law of the Sea', 'transnational');
insert into country_group(id, name, type) values(149, 'CMS', 'transnational');
insert into country_group(id, name, type) values(150, 'Convention on Biological', 'transnational');
insert into country_group(id, name, type) values(151, 'Europe', 'transnational');
insert into country_group(id, name, type) values(152, 'Least Developed Countries', 'transnational');
insert into country_group(id, name, type) values(153, 'G7', 'transnational');
insert into country_group(id, name, type) values(154, 'G20', 'transnational');
insert into country_group(id, name, type) values(155, 'EU', 'transnational');
insert into country_group(id, name, type) values(156, 'Commonwealth', 'transnational');
insert into country_group(id, name, type) values(157, 'ASEAN', 'transnational');
insert into country_group(id, name, type) values(158, 'SIDS', 'transnational');
insert into country_group(id, name, type) values(159, 'APEC', 'transnational');
insert into country_group(id, name, type) values(160, 'Group of 77 and China', 'transnational');
