CREATE TABLE non_member_organisation (
  id serial NOT NULL PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created timestamptz DEFAULT now(),
  modified timestamptz DEFAULT now()
);

INSERT INTO non_member_organisation(name) values('100% Recyclable Pouch');
INSERT INTO non_member_organisation(name) values('11th Hour Racing');
INSERT INTO non_member_organisation(name) values('3M');
INSERT INTO non_member_organisation(name) values('4Ocean Technologies');
INSERT INTO non_member_organisation(name) values('African Council of Religious Leaders-Religions for Peace (ACRL-RfP)');
INSERT INTO non_member_organisation(name) values('African Foundation');
INSERT INTO non_member_organisation(name) values('Agence Française de Developpement (AFD)');
INSERT INTO non_member_organisation(name) values('Airtable');
INSERT INTO non_member_organisation(name) values('Algae Bioplastic');
INSERT INTO non_member_organisation(name) values('Algalita Marine Research and Education');
INSERT INTO non_member_organisation(name) values('Alliance for the Protection of Biodiversity');
INSERT INTO non_member_organisation(name) values('AlphaMERS');
INSERT INTO non_member_organisation(name) values('Amanco Wavin');
INSERT INTO non_member_organisation(name) values('Amazon');
INSERT INTO non_member_organisation(name) values('Amcor Limited');
INSERT INTO non_member_organisation(name) values('American Beverage Association');
INSERT INTO non_member_organisation(name) values('APEC Ocean and Fisheries Working Group (OFWG)');
INSERT INTO non_member_organisation(name) values('Aquário de Ubatuba');
INSERT INTO non_member_organisation(name) values('Argonauta Institute for Coastal and Marine Conservation');
INSERT INTO non_member_organisation(name) values('Ashored');
INSERT INTO non_member_organisation(name) values('Asia-Pacific Economic Cooperation (APEC)');
INSERT INTO non_member_organisation(name) values('Association of Southeast Asian Nations (ASEAN)');
INSERT INTO non_member_organisation(name) values('Australian Government Department of Agriculture, Water and the Environment');
INSERT INTO non_member_organisation(name) values('Australian Government Department of Foreign Affairs and Trade (DFAT)');
INSERT INTO non_member_organisation(name) values('Australian Government Department of the Environment and Energy (DoEE)');
INSERT INTO non_member_organisation(name) values('Autodesk Foundation');
INSERT INTO non_member_organisation(name) values('Baltic Sea Challenge');
INSERT INTO non_member_organisation(name) values('Bandalong Litter Trap');
INSERT INTO non_member_organisation(name) values('Bangladesh Fisheries Research Institute');
INSERT INTO non_member_organisation(name) values('Bank Gospodarstwa Krajowego');
INSERT INTO non_member_organisation(name) values('Bank of America');
INSERT INTO non_member_organisation(name) values('Bantam Ocean Bound Plastic');
INSERT INTO non_member_organisation(name) values('Barber');
INSERT INTO non_member_organisation(name) values('Basel Convention');
INSERT INTO non_member_organisation(name) values('Belize Department of the Environment');
INSERT INTO non_member_organisation(name) values('Benioff Ocean Initiative');
INSERT INTO non_member_organisation(name) values('Berry Global');
INSERT INTO non_member_organisation(name) values('Biogreen');
INSERT INTO non_member_organisation(name) values('Bionic Yarn');
INSERT INTO non_member_organisation(name) values('Birdlife International');
INSERT INTO non_member_organisation(name) values('Black Sea Commission');
INSERT INTO non_member_organisation(name) values('Blue Keepers');
INSERT INTO non_member_organisation(name) values('Blue Marine Foundation');
INSERT INTO non_member_organisation(name) values('Blue Ocean Gear');
INSERT INTO non_member_organisation(name) values('BluePhin');
INSERT INTO non_member_organisation(name) values('BNP Paribas');
INSERT INTO non_member_organisation(name) values('Braskem');
INSERT INTO non_member_organisation(name) values('Brazilian Fund for Biodiversity (FUNBIO)');
INSERT INTO non_member_organisation(name) values('Brazilian Plastic Industry Association (ABIPLAST)');
INSERT INTO non_member_organisation(name) values('British Plastics Federation');
INSERT INTO non_member_organisation(name) values('Buddhist Tzu Chi Foundation Malaysia');
INSERT INTO non_member_organisation(name) values('Bureo');
INSERT INTO non_member_organisation(name) values('Caisse Des Dépôts');
INSERT INTO non_member_organisation(name) values('California Ocean Protection Council');
INSERT INTO non_member_organisation(name) values('Canada''s Environment and Climate Change (ECCC)');
INSERT INTO non_member_organisation(name) values('Canadian Council of Ministers of the Environment');
INSERT INTO non_member_organisation(name) values('Canadian Network for Ocean Education');
INSERT INTO non_member_organisation(name) values('Carrefour');
INSERT INTO non_member_organisation(name) values('Carribean Region - Marine Litter Regional Working Group');
INSERT INTO non_member_organisation(name) values('Cartagena Convention');
INSERT INTO non_member_organisation(name) values('Cassa Depositi e Prestiti');
INSERT INTO non_member_organisation(name) values('Centre for Environment Fisheries and Aquaculture Science (CEFAS)');
INSERT INTO non_member_organisation(name) values('Chanel');
INSERT INTO non_member_organisation(name) values('Circulate Capital');
INSERT INTO non_member_organisation(name) values('City of Helsinki, Finland Environmental protection');
INSERT INTO non_member_organisation(name) values('Clean Currents Coalition');
INSERT INTO non_member_organisation(name) values('Clever Green Limited');
INSERT INTO non_member_organisation(name) values('Climate Emergency Working Group of Association des États Généraux des Étudiants de l’Europe (AEGEE)');
INSERT INTO non_member_organisation(name) values('Closed Loop Partners');
INSERT INTO non_member_organisation(name) values('Coletivação de Limpeza em Mangues, Praias e Rios de Joinville');
INSERT INTO non_member_organisation(name) values('Colgate Palmolive');
INSERT INTO non_member_organisation(name) values('Collectif des Leaders pour le Développement durable de l''Afrique (CLDA)');
INSERT INTO non_member_organisation(name) values('College of Engineering at the University of Georgia');
INSERT INTO non_member_organisation(name) values('Comisión Permanente Del Pacífico Sur (CPPS)');
INSERT INTO non_member_organisation(name) values('Comission for the Conservation of Antarctic Marine Living Resources(CCAMLR)');
INSERT INTO non_member_organisation(name) values('Conservation International');
INSERT INTO non_member_organisation(name) values('Convention for the Protection of the Marine Environment of the North-East Atlantic (OSPAR)');
INSERT INTO non_member_organisation(name) values('Coordinating Ministry for Maritime & Investment Affairs , Kementerian Koordinator Bidang Kemaritiman dan Investasi Republik Indonesia');
INSERT INTO non_member_organisation(name) values('Covanta');
INSERT INTO non_member_organisation(name) values('Cox Enterprises');
INSERT INTO non_member_organisation(name) values('Cristalcopo Descartáveis');
INSERT INTO non_member_organisation(name) values('CVS Health');
INSERT INTO non_member_organisation(name) values('Cyprus Sustainable Tourism Initiative(CSTI)');
INSERT INTO non_member_organisation(name) values('Danone');
INSERT INTO non_member_organisation(name) values('Dart Container Corporation');
INSERT INTO non_member_organisation(name) values('Deep Ocean Stewardship Initiative (DOSI)');
INSERT INTO non_member_organisation(name) values('Department for Business, Energy & Industrial Strategy');
INSERT INTO non_member_organisation(name) values('Department of Environment, Morocco');
INSERT INTO non_member_organisation(name) values('Department of Life Sciences, The University of the West Indies, St. Augustine, Trinidad');
INSERT INTO non_member_organisation(name) values('Development Inc.');
INSERT INTO non_member_organisation(name) values('Didier and Martine Primat Foundation');
INSERT INTO non_member_organisation(name) values('Dirección del Parque Nacional Galápagos');
INSERT INTO non_member_organisation(name) values('Divers Clean Action');
INSERT INTO non_member_organisation(name) values('Dow Chemical Company');
INSERT INTO non_member_organisation(name) values('Duke University Nicholas Institute for Environmental Policy Solutions');
INSERT INTO non_member_organisation(name) values('Earthwatch Europe');
INSERT INTO non_member_organisation(name) values('East China Normal University');
INSERT INTO non_member_organisation(name) values('Ecoalf');
INSERT INTO non_member_organisation(name) values('Ecofriends');
INSERT INTO non_member_organisation(name) values('Ecoocean');
INSERT INTO non_member_organisation(name) values('Ecosurf Institute');
INSERT INTO non_member_organisation(name) values('Ellen MacArthur Foundation (EMF)');
INSERT INTO non_member_organisation(name) values('Ellipsis');
INSERT INTO non_member_organisation(name) values('Empower');
INSERT INTO non_member_organisation(name) values('Environment and Climate Change Canada');
INSERT INTO non_member_organisation(name) values('Environment and Conservation Division, Kiribati');
INSERT INTO non_member_organisation(name) values('European Academies'' Science Advisory Council');
INSERT INTO non_member_organisation(name) values('European Commission');
INSERT INTO non_member_organisation(name) values('European Environment Agency (EEA)');
INSERT INTO non_member_organisation(name) values('European Investment Bank (EIB)');
INSERT INTO non_member_organisation(name) values('European Topic Centre');
INSERT INTO non_member_organisation(name) values('European Topic Centre, University of Malaga (ETC-UMA)');
INSERT INTO non_member_organisation(name) values('European Union (EU)');
INSERT INTO non_member_organisation(name) values('Federal Ministry for Economic Cooperation and Development (BMZ), Germany');
INSERT INTO non_member_organisation(name) values('Federal Ministry of Environment and Tourism, Bosnia and Herzegovina');
INSERT INTO non_member_organisation(name) values('Federal University of Santa Catarina (UFSC)');
INSERT INTO non_member_organisation(name) values('Finnish Environment Institute (SKYE)');
INSERT INTO non_member_organisation(name) values('Fishing for Litter');
INSERT INTO non_member_organisation(name) values('Fishy Filaments');
INSERT INTO non_member_organisation(name) values('Flotilla Foundation');
INSERT INTO non_member_organisation(name) values('Fondation Didier et Martine Primat');
INSERT INTO non_member_organisation(name) values('Fondation pour la Protection de la Biodiversite Marine (FoProBiM)');
INSERT INTO non_member_organisation(name) values('Fonds Aether');
INSERT INTO non_member_organisation(name) values('Foreign Commonwealth and Development Office (FCDO)');
INSERT INTO non_member_organisation(name) values('Foundation Veolia');
INSERT INTO non_member_organisation(name) values('Fourth Session of the United Nations Environment Assembly (UNEA 4)');
INSERT INTO non_member_organisation(name) values('Fraunhofer Institute (Ruhr University Bochum)');
INSERT INTO non_member_organisation(name) values('Fundacion Amiguitos del Oceano');
INSERT INTO non_member_organisation(name) values('G20');
INSERT INTO non_member_organisation(name) values('G7');
INSERT INTO non_member_organisation(name) values('GA Circular');
INSERT INTO non_member_organisation(name) values('Georgia Aquarium');
INSERT INTO non_member_organisation(name) values('German Federal Ministry for the Environment');
INSERT INTO non_member_organisation(name) values('Global Environment Facility (GEF)');
INSERT INTO non_member_organisation(name) values('Global Ghost Gear Initiative (GGGI)');
INSERT INTO non_member_organisation(name) values('Global Methane Initiative');
INSERT INTO non_member_organisation(name) values('Global Pastics Alliance');
INSERT INTO non_member_organisation(name) values('Google Cloud');
INSERT INTO non_member_organisation(name) values('Governing Plastics Network');
INSERT INTO non_member_organisation(name) values('Government of Argentina');
INSERT INTO non_member_organisation(name) values('Government of Australia');
INSERT INTO non_member_organisation(name) values('Government of Belgium');
INSERT INTO non_member_organisation(name) values('Government of Brazil');
INSERT INTO non_member_organisation(name) values('Government of Canada');
INSERT INTO non_member_organisation(name) values('Government of Canada, Department of Environment, Food and Rural Affairs');
INSERT INTO non_member_organisation(name) values('Government of China');
INSERT INTO non_member_organisation(name) values('Government of Croatia');
INSERT INTO non_member_organisation(name) values('Government of Denmark');
INSERT INTO non_member_organisation(name) values('Government of Eritrea');
INSERT INTO non_member_organisation(name) values('Government of Ethiopia');
INSERT INTO non_member_organisation(name) values('Government of Finland');
INSERT INTO non_member_organisation(name) values('Government of France');
INSERT INTO non_member_organisation(name) values('Government of Germany');
INSERT INTO non_member_organisation(name) values('Government of Guyana');
INSERT INTO non_member_organisation(name) values('Government of Iceland');
INSERT INTO non_member_organisation(name) values('Government of India');
INSERT INTO non_member_organisation(name) values('Government of Indonesia');
INSERT INTO non_member_organisation(name) values('Government of Islamic Republic of Iran');
INSERT INTO non_member_organisation(name) values('Government of Israel');
INSERT INTO non_member_organisation(name) values('Government of Italy');
INSERT INTO non_member_organisation(name) values('Government of Japan');
INSERT INTO non_member_organisation(name) values('Government of Madagascar');
INSERT INTO non_member_organisation(name) values('Government of Mexico');
INSERT INTO non_member_organisation(name) values('Government of Morocco');
INSERT INTO non_member_organisation(name) values('Government of Netherlands');
INSERT INTO non_member_organisation(name) values('Government of Norway');
INSERT INTO non_member_organisation(name) values('Government of Pakistan');
INSERT INTO non_member_organisation(name) values('Government of Philippines');
INSERT INTO non_member_organisation(name) values('Government of Romania');
INSERT INTO non_member_organisation(name) values('Government of Russia');
INSERT INTO non_member_organisation(name) values('Government of Singapore');
INSERT INTO non_member_organisation(name) values('Government of Spain');
INSERT INTO non_member_organisation(name) values('Government of Sudan');
INSERT INTO non_member_organisation(name) values('Government of Sweden');
INSERT INTO non_member_organisation(name) values('Government of Thailand');
INSERT INTO non_member_organisation(name) values('Government of The Republic of Korea');
INSERT INTO non_member_organisation(name) values('Government of the Republic of Panama');
INSERT INTO non_member_organisation(name) values('Government of The Republic of South Africa');
INSERT INTO non_member_organisation(name) values('Government of the United Kingdom of Great Britain and Northern Ireland');
INSERT INTO non_member_organisation(name) values('Government of the United States of America');
INSERT INTO non_member_organisation(name) values('Government of Trinidad and Tobago');
INSERT INTO non_member_organisation(name) values('Granta Design');
INSERT INTO non_member_organisation(name) values('Gringgo');
INSERT INTO non_member_organisation(name) values('Haribo');
INSERT INTO non_member_organisation(name) values('Ho''ola One');
INSERT INTO non_member_organisation(name) values('Hubspot');
INSERT INTO non_member_organisation(name) values('Human Environmental Association for Development HEAD Accredited to UNEP & UNEP/MAP');
INSERT INTO non_member_organisation(name) values('IADYS');
INSERT INTO non_member_organisation(name) values('IBM');
INSERT INTO non_member_organisation(name) values('Ichthion');
INSERT INTO non_member_organisation(name) values('Institute European Environmental Policy (IEEP)');
INSERT INTO non_member_organisation(name) values('Institute for Advanced Studies of the University of São Paulo');
INSERT INTO non_member_organisation(name) values('Institute for Sustainable Development and Research (ISDR)');
INSERT INTO non_member_organisation(name) values('Institute of Oceanography and Fisheries');
INSERT INTO non_member_organisation(name) values('Instituto Curicaca');
INSERT INTO non_member_organisation(name) values('Instituto De Crédito Oficial');
INSERT INTO non_member_organisation(name) values('Instituto EcoFaxina');
INSERT INTO non_member_organisation(name) values('Instituto Federal Baiano (IFBAIANO)');
INSERT INTO non_member_organisation(name) values('Instituto Mar Azul');
INSERT INTO non_member_organisation(name) values('Inter-American Development Bank (IDB)');
INSERT INTO non_member_organisation(name) values('International Centre for Climate Change and Development (ICCCAD)');
INSERT INTO non_member_organisation(name) values('International Council of Chemical Association');
INSERT INTO non_member_organisation(name) values('International Finance Corporation (IFC)');
INSERT INTO non_member_organisation(name) values('Interntional Whaling Commission');
INSERT INTO non_member_organisation(name) values('Inter-organization programme for the sound management of chemicals (IOMC)');
INSERT INTO non_member_organisation(name) values('Interreg Baltic Sea Region Programme');
INSERT INTO non_member_organisation(name) values('ITW Hi-Cone');
INSERT INTO non_member_organisation(name) values('Jambeck Research Group');
INSERT INTO non_member_organisation(name) values('Japan Clean Ocean Material Alliance');
INSERT INTO non_member_organisation(name) values('Japan Display Inc. (JDI)');
INSERT INTO non_member_organisation(name) values('Johnson & Johnson');
INSERT INTO non_member_organisation(name) values('Keep America Beautiful');
INSERT INTO non_member_organisation(name) values('Keep the Archipelago Tidy Association (KAT)');
INSERT INTO non_member_organisation(name) values('Kenya Maritime Authority');
INSERT INTO non_member_organisation(name) values('Keurig Dr Pepper');
INSERT INTO non_member_organisation(name) values('Klaxoon');
INSERT INTO non_member_organisation(name) values('Korea Green Growth Trust Fund');
INSERT INTO non_member_organisation(name) values('Kreditanstalt Für Wiederaufbau (KFW)');
INSERT INTO non_member_organisation(name) values('Lifecycle Initiative');
INSERT INTO non_member_organisation(name) values('Litter Trap');
INSERT INTO non_member_organisation(name) values('Lottery Foundation');
INSERT INTO non_member_organisation(name) values('Maj and Tor Nessling Foundation');
INSERT INTO non_member_organisation(name) values('MARELITT Baltic project');
INSERT INTO non_member_organisation(name) values('United Nations Major Group for Children and Youth (MGCY)');
INSERT INTO non_member_organisation(name) values('Marulho Produtos Ecológicos');
INSERT INTO non_member_organisation(name) values('MAVA Foundation');
INSERT INTO non_member_organisation(name) values('Medio Ambiente');
INSERT INTO non_member_organisation(name) values('Microplastic-sensing Drone');
INSERT INTO non_member_organisation(name) values('Microsoft');
INSERT INTO non_member_organisation(name) values('Ministerio del Ambiente y los Recursos Naturales (MARENA)');
INSERT INTO non_member_organisation(name) values('Ministerio del Poder Popular para el Ecosocialismo');
INSERT INTO non_member_organisation(name) values('Ministry for the Ecological Transition (Ministère de la Transition écologique), France');
INSERT INTO non_member_organisation(name) values('Ministry of Climate and Environment, Norway');
INSERT INTO non_member_organisation(name) values('Ministry of Energy, Science, Technology, Environment & Climate Change, Malaysia (MESTEC)');
INSERT INTO non_member_organisation(name) values('Ministry of Environment and Municipality, Qatar');
INSERT INTO non_member_organisation(name) values('Ministry of Environment and Sustainable Development, Argentina');
INSERT INTO non_member_organisation(name) values('Ministry of Environment and Sustainable Development, Colombia');
INSERT INTO non_member_organisation(name) values('Ministry of Environment, Cambodia');
INSERT INTO non_member_organisation(name) values('Ministry of Environment, Lands and Agriculture Development, Kiribati');
INSERT INTO non_member_organisation(name) values('Ministry of Foreign Affairs, Japan (MOFA)');
INSERT INTO non_member_organisation(name) values('Ministry of Foreign Trade and Economic Relations, Bosnia and Herzegovina');
INSERT INTO non_member_organisation(name) values('Ministry of Popular Power for Ecosocialism, Venezuela');
INSERT INTO non_member_organisation(name) values('Ministry of Sustainable Development and Tourism, Montenegro');
INSERT INTO non_member_organisation(name) values('Ministry of the Environment, Brazil');
INSERT INTO non_member_organisation(name) values('Ministry of the Environment, Ecuador');
INSERT INTO non_member_organisation(name) values('Ministry of the Environment, Finland');
INSERT INTO non_member_organisation(name) values('Ministry of the Environment, Japan');
INSERT INTO non_member_organisation(name) values('Ministry of Tourism and Environment, Albania');
INSERT INTO non_member_organisation(name) values('Mohammed VI Foundation for the Protection of the Environment');
INSERT INTO non_member_organisation(name) values('Monaco Foundation');
INSERT INTO non_member_organisation(name) values('Monaco Private Label');
INSERT INTO non_member_organisation(name) values('Monte Carlo Société des Bains de Mer');
INSERT INTO non_member_organisation(name) values('Morgan Stanley');
INSERT INTO non_member_organisation(name) values('Mott MacDonald');
INSERT INTO non_member_organisation(name) values('My Little Plastic Footprint');
INSERT INTO non_member_organisation(name) values('Nairobi Convention');
INSERT INTO non_member_organisation(name) values('National Environment Commission, Bhutan');
INSERT INTO non_member_organisation(name) values('National Geographic');
INSERT INTO non_member_organisation(name) values('National Geographic Society');
INSERT INTO non_member_organisation(name) values('National Ocean Service');
INSERT INTO non_member_organisation(name) values('National Research Council of Canada');
INSERT INTO non_member_organisation(name) values('National Science Foundation');
INSERT INTO non_member_organisation(name) values('Nestlé');
INSERT INTO non_member_organisation(name) values('Nestlé Waters');
INSERT INTO non_member_organisation(name) values('Nestlé Waters North America');
INSERT INTO non_member_organisation(name) values('Net Your Problem');
INSERT INTO non_member_organisation(name) values('Net-Works');
INSERT INTO non_member_organisation(name) values('New Zealand Ministry of Environment');
INSERT INTO non_member_organisation(name) values('New Zealand Product Stewardship Council');
INSERT INTO non_member_organisation(name) values('Nipe Fagio');
INSERT INTO non_member_organisation(name) values('Nordsense');
INSERT INTO non_member_organisation(name) values('Northland Regional Council (NRC) of New Zealand');
INSERT INTO non_member_organisation(name) values('Northwest Pacific Action Plan (NOWPAP)');
INSERT INTO non_member_organisation(name) values('Norton Point');
INSERT INTO non_member_organisation(name) values('Norwegian Agency for Development Cooperation (NORAD)');
INSERT INTO non_member_organisation(name) values('Norwegian Cruise Line Holdings LTD.');
INSERT INTO non_member_organisation(name) values('Norwegian Embassy');
INSERT INTO non_member_organisation(name) values('Norwegian Retailers'' Environment Fund');
INSERT INTO non_member_organisation(name) values('NOSCA Clean Oceans');
INSERT INTO non_member_organisation(name) values('Nova Scotia Beach Garbage Awareness');
INSERT INTO non_member_organisation(name) values('Nuclear and Energy Research Institute (IPEN)');
INSERT INTO non_member_organisation(name) values('Observatory of Menorca (OBSAM)');
INSERT INTO non_member_organisation(name) values('Ocean Bound Plastic Certifications');
INSERT INTO non_member_organisation(name) values('Ocean Polymers');
INSERT INTO non_member_organisation(name) values('Ocean Sole');
INSERT INTO non_member_organisation(name) values('OceanBound Plastics');
INSERT INTO non_member_organisation(name) values('OceanCycle');
INSERT INTO non_member_organisation(name) values('Oceanworks');
INSERT INTO non_member_organisation(name) values('Odyssey Impact Investments');
INSERT INTO non_member_organisation(name) values('Office Burundais pour la Protection de l''environnement ( OBPE)');
INSERT INTO non_member_organisation(name) values('Official Development Assistance (ODA)');
INSERT INTO non_member_organisation(name) values('One Earth - One Ocean');
INSERT INTO non_member_organisation(name) values('Operation Clean Sweep');
INSERT INTO non_member_organisation(name) values('Orca Sound Project');
INSERT INTO non_member_organisation(name) values('Organisation Publique');
INSERT INTO non_member_organisation(name) values('Our Sea of East Asia Network (OSEAN)');
INSERT INTO non_member_organisation(name) values('Palmy''s Plastic Pollution Challenge');
INSERT INTO non_member_organisation(name) values('Parley');
INSERT INTO non_member_organisation(name) values('Partnerships in Environmental Management for the Seas of East Asia (PEMSEA)');
INSERT INTO non_member_organisation(name) values('Pegasys');
INSERT INTO non_member_organisation(name) values('Pepsico');
INSERT INTO non_member_organisation(name) values('Permanent Secretariat of the Commission on the Protection of the Black Sea Against Pollution');
INSERT INTO non_member_organisation(name) values('PingMe');
INSERT INTO non_member_organisation(name) values('Pinovo');
INSERT INTO non_member_organisation(name) values('Planet Patrol App');
INSERT INTO non_member_organisation(name) values('Planet Tracker');
INSERT INTO non_member_organisation(name) values('Plastic Cup');
INSERT INTO non_member_organisation(name) values('Plastic Free Israel');
INSERT INTO non_member_organisation(name) values('Plastic Solutions Fund');
INSERT INTO non_member_organisation(name) values('Plastic Soup Foundation');
INSERT INTO non_member_organisation(name) values('Plastic Soup Surfer');
INSERT INTO non_member_organisation(name) values('Plastic Vortex');
INSERT INTO non_member_organisation(name) values('Plasticoin');
INSERT INTO non_member_organisation(name) values('Plastics Europe');
INSERT INTO non_member_organisation(name) values('Plastivida');
INSERT INTO non_member_organisation(name) values('Plastix');
INSERT INTO non_member_organisation(name) values('Plymouth Marine Laboratory');
INSERT INTO non_member_organisation(name) values('Procter & Gamble');
INSERT INTO non_member_organisation(name) values('Programme of the Sustainable Ocean Alliance (SOA)');
INSERT INTO non_member_organisation(name) values('Project STOP');
INSERT INTO non_member_organisation(name) values('Projeto de Monitoramento de Praias da Bacia de Santos (PMP-BS)');
INSERT INTO non_member_organisation(name) values('Projeto Somos do Mar');
INSERT INTO non_member_organisation(name) values('Protection of the Arctic Marine Environemt (PAME)');
INSERT INTO non_member_organisation(name) values('Quantis');
INSERT INTO non_member_organisation(name) values('ReCleanSea');
INSERT INTO non_member_organisation(name) values('Rede de Coleções Didáticas e Científicas do Lixo Marinho (ReCOLIXO)');
INSERT INTO non_member_organisation(name) values('Rede Ibero-americana de Gestão e Certificação de Praias (PROPLAYAS)');
INSERT INTO non_member_organisation(name) values('Regional Capacity Development Consultancy');
INSERT INTO non_member_organisation(name) values('Regional Organization for the Conservation of the Environment of the Red Sea and Gulf of Aden (PERSGA)');
INSERT INTO non_member_organisation(name) values('Renew Oceans');
INSERT INTO non_member_organisation(name) values('rePurpose');
INSERT INTO non_member_organisation(name) values('RePurpose Global');
INSERT INTO non_member_organisation(name) values('REV Ocean Science and Innovation Committee');
INSERT INTO non_member_organisation(name) values('Richard Lounsbery Foundation');
INSERT INTO non_member_organisation(name) values('Rozalia Project for a Clean Ocean');
INSERT INTO non_member_organisation(name) values('RPC Group Plc');
INSERT INTO non_member_organisation(name) values('Safegear');
INSERT INTO non_member_organisation(name) values('Saint Lucia National Conservation Fund (SLUNCF)');
INSERT INTO non_member_organisation(name) values('Sandals Foundation');
INSERT INTO non_member_organisation(name) values('Sao Paulo State Secretariat for Infrastructure and Environment');
INSERT INTO non_member_organisation(name) values('São Paulo State University');
INSERT INTO non_member_organisation(name) values('Scientific Committee on Antarctic Research');
INSERT INTO non_member_organisation(name) values('Scientific Committee on Oceanic Research');
INSERT INTO non_member_organisation(name) values('Sea Shepherd');
INSERT INTO non_member_organisation(name) values('Seabin Smart Tech including Pollution Index');
INSERT INTO non_member_organisation(name) values('SeaChange');
INSERT INTO non_member_organisation(name) values('SEAQUAL');
INSERT INTO non_member_organisation(name) values('Searious Business');
INSERT INTO non_member_organisation(name) values('Second Muse');
INSERT INTO non_member_organisation(name) values('Secretariat of Infrastructure and Environment of the State of São Paulo');
INSERT INTO non_member_organisation(name) values('Secretariat of the Basel, Rotterdam and Stockholm Conventions United Nations Environment Programme (UNEP)');
INSERT INTO non_member_organisation(name) values('Shanghai Rendu OCENA NPO Development Center');
INSERT INTO non_member_organisation(name) values('Sheavly Consultants');
INSERT INTO non_member_organisation(name) values('Somalia African Solutions');
INSERT INTO non_member_organisation(name) values('South Asian Seas (SAS) Region');
INSERT INTO non_member_organisation(name) values('South South North');
INSERT INTO non_member_organisation(name) values('Stand UPET');
INSERT INTO non_member_organisation(name) values('Starbucks');
INSERT INTO non_member_organisation(name) values('State Agency on Environment Protection and Forestry, Kyrgyzstan');
INSERT INTO non_member_organisation(name) values('Stockholm Environment Institute (SEI)');
INSERT INTO non_member_organisation(name) values('StormX Netting Trash Trap');
INSERT INTO non_member_organisation(name) values('Strength in Diversity Development Centre');
INSERT INTO non_member_organisation(name) values('Stripe');
INSERT INTO non_member_organisation(name) values('Surfrider Foundation');
INSERT INTO non_member_organisation(name) values('Swedish Agency for Marine and Water Management');
INSERT INTO non_member_organisation(name) values('Swedish International Development Cooperation Agency (SIDA)');
INSERT INTO non_member_organisation(name) values('Swedish Postcode Foundation');
INSERT INTO non_member_organisation(name) values('Swiss Federal Institute of Aquatic Science and Technology, Department of Sanitation, Water and Solid Waste for Development (EAWAG, SANDEC)');
INSERT INTO non_member_organisation(name) values('SYSTEMIQ');
INSERT INTO non_member_organisation(name) values('Tara Expeditions Foundation');
INSERT INTO non_member_organisation(name) values('Taupo District Council');
INSERT INTO non_member_organisation(name) values('Tearfund');
INSERT INTO non_member_organisation(name) values('Technical University of Denmark');
INSERT INTO non_member_organisation(name) values('The 3R Initiative');
INSERT INTO non_member_organisation(name) values('The Blue Barriers');
INSERT INTO non_member_organisation(name) values('The Circulate Initiative');
INSERT INTO non_member_organisation(name) values('The Coca-Cola Company');
INSERT INTO non_member_organisation(name) values('The Coca-Cola Foundation');
INSERT INTO non_member_organisation(name) values('The Consumer Goods Forum');
INSERT INTO non_member_organisation(name) values('The Coordinating Body on the Seas of East Asia (COBSEA)');
INSERT INTO non_member_organisation(name) values('The David and Lucile Packard Foundation');
INSERT INTO non_member_organisation(name) values('The Dow Chemical Company');
INSERT INTO non_member_organisation(name) values('The European Investment Bank');
INSERT INTO non_member_organisation(name) values('The Global Partnership on Marine Litter (GPML)');
INSERT INTO non_member_organisation(name) values('The Great Bubble Barrier');
INSERT INTO non_member_organisation(name) values('The Incubation Network');
INSERT INTO non_member_organisation(name) values('The Institute of Environmental Science and Research (ESR)');
INSERT INTO non_member_organisation(name) values('The Intergovernmental Oceanographic (IOC) Commission of United Nations Educational, Scientific and Cultural Organization (UNESCO)');
INSERT INTO non_member_organisation(name) values('The International Environmental Technology Centre (IETC)');
INSERT INTO non_member_organisation(name) values('The Litter Gitter');
INSERT INTO non_member_organisation(name) values('The Litterboom Project');
INSERT INTO non_member_organisation(name) values('The Marine Litter Round Table');
INSERT INTO non_member_organisation(name) values('The Marine Mammal Center');
INSERT INTO non_member_organisation(name) values('The Mediterranean Action Plan (MAP)');
INSERT INTO non_member_organisation(name) values('The National Academies of Science, Engineering and Medicine');
INSERT INTO non_member_organisation(name) values('The Ocean Cleanup');
INSERT INTO non_member_organisation(name) values('Pew Charitable Trust');
INSERT INTO non_member_organisation(name) values('The Procter & Gamble Company');
INSERT INTO non_member_organisation(name) values('The Recycling Partnership');
INSERT INTO non_member_organisation(name) values('The S Group');
INSERT INTO non_member_organisation(name) values('The Sea Cleaners');
INSERT INTO non_member_organisation(name) values('The United Nations Environment Programme - Caribbean Environment Programme (UNEP-CEP)');
INSERT INTO non_member_organisation(name) values('Third Sector organization');
INSERT INTO non_member_organisation(name) values('Third session of the United Nations Environment Assembly (UNEA 3)');
INSERT INTO non_member_organisation(name) values('Thomsea');
INSERT INTO non_member_organisation(name) values('Together Cyprus');
INSERT INTO non_member_organisation(name) values('Trash booms');
INSERT INTO non_member_organisation(name) values('Trash Wheel');
INSERT INTO non_member_organisation(name) values('Trinet');
INSERT INTO non_member_organisation(name) values('Tripla Difesa Onlus');
INSERT INTO non_member_organisation(name) values('UFSC sem Plástico (UFSC Plastic Free)');
INSERT INTO non_member_organisation(name) values('Unilever');
INSERT INTO non_member_organisation(name) values('United Kingdom Department for International Development (DFID)');
INSERT INTO non_member_organisation(name) values('United Nations Children’s Emergency Fund (UNICEF)');
INSERT INTO non_member_organisation(name) values('United Nations Conference on Trade and Development (UNCTAD)');
INSERT INTO non_member_organisation(name) values('United Nations Development Programme (UNDP)');
INSERT INTO non_member_organisation(name) values('United Nations Economic and Social Commission for Asia and the Pacific (UNESCAP)');
INSERT INTO non_member_organisation(name) values('United Nations Educational, Scientific and Cultural Organization (UNESCO) Chair on Ocean Sustainability');
INSERT INTO non_member_organisation(name) values('United Nations Environment Programme (UNEP) Regional Office for Latin America and the Caribbean (ROLAC)');
INSERT INTO non_member_organisation(name) values('United Nations Industrial Development Organization (UNIDO)');
INSERT INTO non_member_organisation(name) values('United States Agency for International Development (USAID)');
INSERT INTO non_member_organisation(name) values('United States Department of Commerce');
INSERT INTO non_member_organisation(name) values('United States State Department');
INSERT INTO non_member_organisation(name) values('Univali - Unidade Penha');
INSERT INTO non_member_organisation(name) values('Universidad Autónoma Metropolitana');
INSERT INTO non_member_organisation(name) values('Universidad Técnica de Manabí');
INSERT INTO non_member_organisation(name) values('Universidade do Estado do Rio de Janeiro (UERJ)');
INSERT INTO non_member_organisation(name) values('Universidade do Vale do Itajaí (UNIVALI)');
INSERT INTO non_member_organisation(name) values('Universidade Federal do Pará (UFPA)');
INSERT INTO non_member_organisation(name) values('Universidade Federal Rural do Semi-Arido');
INSERT INTO non_member_organisation(name) values('University of Georgia');
INSERT INTO non_member_organisation(name) values('University of Leeds');
INSERT INTO non_member_organisation(name) values('University of Montenegro - Institute of Marine Biology (UoM, IMB)');
INSERT INTO non_member_organisation(name) values('University of Nairobi');
INSERT INTO non_member_organisation(name) values('University of Plymouth');
INSERT INTO non_member_organisation(name) values('University of Santa Cecília');
INSERT INTO non_member_organisation(name) values('University of São Paulo');
INSERT INTO non_member_organisation(name) values('University of Surrey');
INSERT INTO non_member_organisation(name) values('Veolia Environnement S.A.');
INSERT INTO non_member_organisation(name) values('Waitrose');
INSERT INTO non_member_organisation(name) values('Walmart');
INSERT INTO non_member_organisation(name) values('Waste and Resources Action Programme (WRiAP)');
INSERT INTO non_member_organisation(name) values('WasteShark');
INSERT INTO non_member_organisation(name) values('Wasteware');
INSERT INTO non_member_organisation(name) values('Welfare Togo');
INSERT INTO non_member_organisation(name) values('Wildlife Conservation Society');
INSERT INTO non_member_organisation(name) values('Wilson Sonsini');
INSERT INTO non_member_organisation(name) values('World Bank');
INSERT INTO non_member_organisation(name) values('World Economic Forum (WEF)');
INSERT INTO non_member_organisation(name) values('World Health Organization (WHO)');
INSERT INTO non_member_organisation(name) values('World Plastics Council');
INSERT INTO non_member_organisation(name) values('World Wildlife Fund (WWF)');
INSERT INTO non_member_organisation(name) values('Wuhan University of Technology');
INSERT INTO non_member_organisation(name) values('Youth Development Organization(YODO)');
