DROP VIEW v_organisation_association CASCADE;
--;;
DROP TABLE organisation_resource CASCADE;
--;;
DROP TABLE organisation_event CASCADE;
--;;
DROP TABLE organisation_technology CASCADE;
--;;
DROP TABLE organisation_policy CASCADE;
--;;
DROP TABLE organisation_project CASCADE;