ALTER TYPE event_association ADD VALUE IF NOT EXISTS 'implementor';
--;;
ALTER TYPE event_association ADD VALUE IF NOT EXISTS 'owner';
--;;
ALTER TYPE event_association ADD VALUE IF NOT EXISTS 'partner';
--;;
ALTER TYPE event_association ADD VALUE IF NOT EXISTS 'donor';
--;;
ALTER TYPE policy_association ADD VALUE IF NOT EXISTS 'owner';
--;;
ALTER TYPE policy_association ADD VALUE IF NOT EXISTS 'partner';
--;;
ALTER TYPE policy_association ADD VALUE IF NOT EXISTS 'donor';