BEGIN;
--;;
ALTER TABLE IF EXISTS resource
  ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT FALSE;
--;;
ALTER TABLE IF EXISTS policy
  ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT FALSE;
--;;
ALTER TABLE IF EXISTS initiative
  ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT FALSE;
--;;
ALTER TABLE IF EXISTS technology
  ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT FALSE;
--;;
ALTER TABLE IF EXISTS event
  ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT FALSE;
--;;
COMMIT;