BEGIN;
--;;
ALTER TABLE resource
ADD COLUMN brs_api_id TEXT UNIQUE,
ADD COLUMN brs_api_modified TIMESTAMP WITHOUT TIME ZONE;
--;;
ALTER TABLE event
ADD COLUMN brs_api_id TEXT UNIQUE,
ADD COLUMN brs_api_modified TIMESTAMP WITHOUT TIME ZONE,
ADD COLUMN link_registration TEXT;
--;;
ALTER TABLE initiative
ADD COLUMN brs_api_id TEXT UNIQUE,
ADD COLUMN brs_api_modified TIMESTAMP WITHOUT TIME ZONE,
ADD COLUMN start_date TIMESTAMP WITHOUT TIME ZONE,
ADD COLUMN end_date TIMESTAMP WITHOUT TIME ZONE,
ADD COLUMN status TEXT,
ADD COLUMN objectives TEXT,
ADD COLUMN activities TEXT;
--;;
ALTER TABLE event
ALTER COLUMN start_date DROP NOT NULL,
ALTER COLUMN end_date DROP NOT NULL,
ALTER COLUMN description DROP NOT NULL;
--;;
ALTER TABLE initiative_geo_coverage
DROP CONSTRAINT initiative_geo_coverage_country_fkey,
DROP CONSTRAINT initiative_geo_coverage_country_group_fkey,
DROP CONSTRAINT initiative_geo_coverage_initiative_fkey;
--;;
ALTER TABLE initiative_geo_coverage
ADD CONSTRAINT initiative_geo_coverage_country_fkey FOREIGN KEY (country) REFERENCES country(id) ON DELETE CASCADE,
ADD CONSTRAINT initiative_geo_coverage_country_group_fkey FOREIGN KEY (country_group) REFERENCES country_group(id) ON DELETE CASCADE,
ADD CONSTRAINT initiative_geo_coverage_initiative_fkey FOREIGN KEY (initiative) REFERENCES initiative(id) ON DELETE CASCADE;
--;;
ALTER TABLE event_geo_coverage
DROP CONSTRAINT event_geo_coverage_country_fkey,
DROP CONSTRAINT event_geo_coverage_country_group_fkey,
DROP CONSTRAINT event_geo_coverage_event_fkey;
--;;
ALTER TABLE event_geo_coverage
ADD CONSTRAINT event_geo_coverage_country_fkey FOREIGN KEY (country) REFERENCES country(id) ON DELETE CASCADE,
ADD CONSTRAINT event_geo_coverage_country_group_fkey FOREIGN KEY (country_group) REFERENCES country_group(id) ON DELETE CASCADE,
ADD CONSTRAINT event_geo_coverage_event_fkey FOREIGN KEY (event) REFERENCES event(id) ON DELETE CASCADE;
--;;
ALTER TABLE resource_geo_coverage
DROP CONSTRAINT resource_geo_coverage_country_fkey,
DROP CONSTRAINT resource_geo_coverage_country_group_fkey,
DROP CONSTRAINT resource_geo_coverage_resource_fkey;
--;;
ALTER TABLE resource_geo_coverage
ADD CONSTRAINT resource_geo_coverage_country_fkey FOREIGN KEY (country) REFERENCES country(id) ON DELETE CASCADE,
ADD CONSTRAINT resource_geo_coverage_country_group_fkey FOREIGN KEY (country_group) REFERENCES country_group(id) ON DELETE CASCADE,
ADD CONSTRAINT resource_geo_coverage_resource_fkey FOREIGN KEY (resource) REFERENCES resource(id) ON DELETE CASCADE;
--;;
ALTER TABLE technology_geo_coverage
DROP CONSTRAINT technology_geo_coverage_country_fkey,
DROP CONSTRAINT technology_geo_coverage_country_group_fkey,
DROP CONSTRAINT technology_geo_coverage_technology_fkey;
--;;
ALTER TABLE technology_geo_coverage
ADD CONSTRAINT technology_geo_coverage_country_fkey FOREIGN KEY (country) REFERENCES country(id) ON DELETE CASCADE,
ADD CONSTRAINT technology_geo_coverage_country_group_fkey FOREIGN KEY (country_group) REFERENCES country_group(id) ON DELETE CASCADE,
ADD CONSTRAINT technology_geo_coverage_technology_fkey FOREIGN KEY (technology) REFERENCES technology(id) ON DELETE CASCADE;
--;;
ALTER TABLE policy_geo_coverage
DROP CONSTRAINT policy_geo_coverage_country_fkey,
DROP CONSTRAINT policy_geo_coverage_country_group_fkey,
DROP CONSTRAINT policy_geo_coverage_policy_fkey;
--;;
ALTER TABLE policy_geo_coverage
ADD CONSTRAINT policy_geo_coverage_country_fkey FOREIGN KEY (country) REFERENCES country(id) ON DELETE CASCADE,
ADD CONSTRAINT policy_geo_coverage_country_group_fkey FOREIGN KEY (country_group) REFERENCES country_group(id) ON DELETE CASCADE,
ADD CONSTRAINT policy_geo_coverage_policy_fkey FOREIGN KEY (policy) REFERENCES policy(id) ON DELETE CASCADE;
--;;
INSERT INTO tag_category(category)
VALUES('brs api');
--;;
ALTER TABLE country
RENAME COLUMN iso_code TO iso_code_a3;
--;;
ALTER TABLE country
ADD COLUMN iso_code_a2 CHARACTER VARYING(2);
--;;
UPDATE country SET iso_code_a2 = 'MQ' WHERE iso_code_a3 = 'MTQ';
--;;
UPDATE country SET iso_code_a2 = 'GY' WHERE iso_code_a3 = 'GUY';
--;;
UPDATE country SET iso_code_a2 = 'TG' WHERE iso_code_a3 = 'TGO';
--;;
UPDATE country SET iso_code_a2 = 'VC' WHERE iso_code_a3 = 'VCT';
--;;
UPDATE country SET iso_code_a2 = 'MF' WHERE iso_code_a3 = 'MAF';
--;;
UPDATE country SET iso_code_a2 = 'BF' WHERE iso_code_a3 = 'BFA';
--;;
UPDATE country SET iso_code_a2 = 'AM' WHERE iso_code_a3 = 'ARM';
--;;
UPDATE country SET iso_code_a2 = 'ID' WHERE iso_code_a3 = 'IDN';
--;;
UPDATE country SET iso_code_a2 = 'MW' WHERE iso_code_a3 = 'MWI';
--;;
UPDATE country SET iso_code_a2 = 'AT' WHERE iso_code_a3 = 'AUT';
--;;
UPDATE country SET iso_code_a2 = 'BD' WHERE iso_code_a3 = 'BGD';
--;;
UPDATE country SET iso_code_a2 = 'MV' WHERE iso_code_a3 = 'MDV';
--;;
UPDATE country SET iso_code_a2 = 'WS' WHERE iso_code_a3 = 'WSM';
--;;
UPDATE country SET iso_code_a2 = 'MA' WHERE iso_code_a3 = 'MAR';
--;;
UPDATE country SET iso_code_a2 = 'RS' WHERE iso_code_a3 = 'SRB';
--;;
UPDATE country SET iso_code_a2 = 'TK' WHERE iso_code_a3 = 'TKL';
--;;
UPDATE country SET iso_code_a2 = 'IR' WHERE iso_code_a3 = 'IRN';
--;;
UPDATE country SET iso_code_a2 = 'SY' WHERE iso_code_a3 = 'SYR';
--;;
UPDATE country SET iso_code_a2 = 'JO' WHERE iso_code_a3 = 'JOR';
--;;
UPDATE country SET iso_code_a2 = 'MZ' WHERE iso_code_a3 = 'MOZ';
--;;
UPDATE country SET iso_code_a2 = 'UG' WHERE iso_code_a3 = 'UGA';
--;;
UPDATE country SET iso_code_a2 = 'CG' WHERE iso_code_a3 = 'COG';
--;;
UPDATE country SET iso_code_a2 = 'GS' WHERE iso_code_a3 = 'SGS';
--;;
UPDATE country SET iso_code_a2 = 'PL' WHERE iso_code_a3 = 'POL';
--;;
UPDATE country SET iso_code_a2 = 'OM' WHERE iso_code_a3 = 'OMN';
--;;
UPDATE country SET iso_code_a2 = 'MR' WHERE iso_code_a3 = 'MRT';
--;;
UPDATE country SET iso_code_a2 = 'BM' WHERE iso_code_a3 = 'BMU';
--;;
UPDATE country SET iso_code_a2 = 'BE' WHERE iso_code_a3 = 'BEL';
--;;
UPDATE country SET iso_code_a2 = 'SC' WHERE iso_code_a3 = 'SYC';
--;;
UPDATE country SET iso_code_a2 = 'CC' WHERE iso_code_a3 = 'CCK';
--;;
UPDATE country SET iso_code_a2 = 'GB' WHERE iso_code_a3 = 'GBR';
--;;
UPDATE country SET iso_code_a2 = 'PM' WHERE iso_code_a3 = 'SPM';
--;;
UPDATE country SET iso_code_a2 = 'DO' WHERE iso_code_a3 = 'DOM';
--;;
UPDATE country SET iso_code_a2 = 'MN' WHERE iso_code_a3 = 'MNG';
--;;
UPDATE country SET iso_code_a2 = 'CY' WHERE iso_code_a3 = 'CYP';
--;;
UPDATE country SET iso_code_a2 = 'SI' WHERE iso_code_a3 = 'SVN';
--;;
UPDATE country SET iso_code_a2 = 'LC' WHERE iso_code_a3 = 'LCA';
--;;
UPDATE country SET iso_code_a2 = 'SL' WHERE iso_code_a3 = 'SLE';
--;;
UPDATE country SET iso_code_a2 = 'YE' WHERE iso_code_a3 = 'YEM';
--;;
UPDATE country SET iso_code_a2 = 'MH' WHERE iso_code_a3 = 'MHL';
--;;
UPDATE country SET iso_code_a2 = 'SE' WHERE iso_code_a3 = 'SWE';
--;;
UPDATE country SET iso_code_a2 = 'AE' WHERE iso_code_a3 = 'ARE';
--;;
UPDATE country SET iso_code_a2 = 'EG' WHERE iso_code_a3 = 'EGY';
--;;
UPDATE country SET iso_code_a2 = 'ZA' WHERE iso_code_a3 = 'ZAF';
--;;
UPDATE country SET iso_code_a2 = 'FI' WHERE iso_code_a3 = 'FIN';
--;;
UPDATE country SET iso_code_a2 = 'IQ' WHERE iso_code_a3 = 'IRQ';
--;;
UPDATE country SET iso_code_a2 = 'GP' WHERE iso_code_a3 = 'GLP';
--;;
UPDATE country SET iso_code_a2 = 'CZ' WHERE iso_code_a3 = 'CZE';
--;;
UPDATE country SET iso_code_a2 = 'TM' WHERE iso_code_a3 = 'TKM';
--;;
UPDATE country SET iso_code_a2 = 'TC' WHERE iso_code_a3 = 'TCA';
--;;
UPDATE country SET iso_code_a2 = 'MC' WHERE iso_code_a3 = 'MCO';
--;;
UPDATE country SET iso_code_a2 = 'BY' WHERE iso_code_a3 = 'BLR';
--;;
UPDATE country SET iso_code_a2 = 'KY' WHERE iso_code_a3 = 'CYM';
--;;
UPDATE country SET iso_code_a2 = 'NU' WHERE iso_code_a3 = 'NIU';
--;;
UPDATE country SET iso_code_a2 = 'CV' WHERE iso_code_a3 = 'CPV';
--;;
UPDATE country SET iso_code_a2 = 'FO' WHERE iso_code_a3 = 'FRO';
--;;
UPDATE country SET iso_code_a2 = 'GG' WHERE iso_code_a3 = 'GGY';
--;;
UPDATE country SET iso_code_a2 = 'MO' WHERE iso_code_a3 = 'MAC';
--;;
UPDATE country SET iso_code_a2 = 'CN' WHERE iso_code_a3 = 'CHN';
--;;
UPDATE country SET iso_code_a2 = 'LT' WHERE iso_code_a3 = 'LTU';
--;;
UPDATE country SET iso_code_a2 = 'BV' WHERE iso_code_a3 = 'BVT';
--;;
UPDATE country SET iso_code_a2 = 'TW' WHERE iso_code_a3 = 'TWN';
--;;
UPDATE country SET iso_code_a2 = 'CR' WHERE iso_code_a3 = 'CRI';
--;;
UPDATE country SET iso_code_a2 = 'VN' WHERE iso_code_a3 = 'VNM';
--;;
UPDATE country SET iso_code_a2 = 'WF' WHERE iso_code_a3 = 'WLF';
--;;
UPDATE country SET iso_code_a2 = 'HT' WHERE iso_code_a3 = 'HTI';
--;;
UPDATE country SET iso_code_a2 = 'LK' WHERE iso_code_a3 = 'LKA';
--;;
UPDATE country SET iso_code_a2 = 'AR' WHERE iso_code_a3 = 'ARG';
--;;
UPDATE country SET iso_code_a2 = 'LV' WHERE iso_code_a3 = 'LVA';
--;;
UPDATE country SET iso_code_a2 = 'DJ' WHERE iso_code_a3 = 'DJI';
--;;
UPDATE country SET iso_code_a2 = 'PF' WHERE iso_code_a3 = 'PYF';
--;;
UPDATE country SET iso_code_a2 = 'ZW' WHERE iso_code_a3 = 'ZWE';
--;;
UPDATE country SET iso_code_a2 = 'NF' WHERE iso_code_a3 = 'NFK';
--;;
UPDATE country SET iso_code_a2 = 'LY' WHERE iso_code_a3 = 'LBY';
--;;
UPDATE country SET iso_code_a2 = 'SA' WHERE iso_code_a3 = 'SAU';
--;;
UPDATE country SET iso_code_a2 = 'VG' WHERE iso_code_a3 = 'VGB';
--;;
UPDATE country SET iso_code_a2 = 'GM' WHERE iso_code_a3 = 'GMB';
--;;
UPDATE country SET iso_code_a2 = 'TV' WHERE iso_code_a3 = 'TUV';
--;;
UPDATE country SET iso_code_a2 = 'BJ' WHERE iso_code_a3 = 'BEN';
--;;
UPDATE country SET iso_code_a2 = 'GT' WHERE iso_code_a3 = 'GTM';
--;;
UPDATE country SET iso_code_a2 = 'RO' WHERE iso_code_a3 = 'ROU';
--;;
UPDATE country SET iso_code_a2 = 'EH' WHERE iso_code_a3 = 'ESH';
--;;
UPDATE country SET iso_code_a2 = 'KG' WHERE iso_code_a3 = 'KGZ';
--;;
UPDATE country SET iso_code_a2 = 'DE' WHERE iso_code_a3 = 'DEU';
--;;
UPDATE country SET iso_code_a2 = 'FJ' WHERE iso_code_a3 = 'FJI';
--;;
UPDATE country SET iso_code_a2 = 'MK' WHERE iso_code_a3 = 'MKD';
--;;
UPDATE country SET iso_code_a2 = 'HR' WHERE iso_code_a3 = 'HRV';
--;;
UPDATE country SET iso_code_a2 = 'HU' WHERE iso_code_a3 = 'HUN';
--;;
UPDATE country SET iso_code_a2 = 'SH' WHERE iso_code_a3 = 'SHN';
--;;
UPDATE country SET iso_code_a2 = 'SM' WHERE iso_code_a3 = 'SMR';
--;;
UPDATE country SET iso_code_a2 = 'IN' WHERE iso_code_a3 = 'IND';
--;;
UPDATE country SET iso_code_a2 = 'GQ' WHERE iso_code_a3 = 'GNQ';
--;;
UPDATE country SET iso_code_a2 = 'NP' WHERE iso_code_a3 = 'NPL';
--;;
UPDATE country SET iso_code_a2 = 'PR' WHERE iso_code_a3 = 'PRI';
--;;
UPDATE country SET iso_code_a2 = 'AF' WHERE iso_code_a3 = 'AFG';
--;;
UPDATE country SET iso_code_a2 = 'PG' WHERE iso_code_a3 = 'PNG';
--;;
UPDATE country SET iso_code_a2 = 'TF' WHERE iso_code_a3 = 'ATF';
--;;
UPDATE country SET iso_code_a2 = 'ZM' WHERE iso_code_a3 = 'ZMB';
--;;
UPDATE country SET iso_code_a2 = 'RE' WHERE iso_code_a3 = 'REU';
--;;
UPDATE country SET iso_code_a2 = 'PT' WHERE iso_code_a3 = 'PRT';
--;;
UPDATE country SET iso_code_a2 = 'GF' WHERE iso_code_a3 = 'GUF';
--;;
UPDATE country SET iso_code_a2 = 'UA' WHERE iso_code_a3 = 'UKR';
--;;
UPDATE country SET iso_code_a2 = 'MS' WHERE iso_code_a3 = 'MSR';
--;;
UPDATE country SET iso_code_a2 = 'SR' WHERE iso_code_a3 = 'SUR';
--;;
UPDATE country SET iso_code_a2 = 'BG' WHERE iso_code_a3 = 'BGR';
--;;
UPDATE country SET iso_code_a2 = 'TN' WHERE iso_code_a3 = 'TUN';
--;;
UPDATE country SET iso_code_a2 = 'GH' WHERE iso_code_a3 = 'GHA';
--;;
UPDATE country SET iso_code_a2 = 'MD' WHERE iso_code_a3 = 'MDA';
--;;
UPDATE country SET iso_code_a2 = 'AO' WHERE iso_code_a3 = 'AGO';
--;;
UPDATE country SET iso_code_a2 = 'MT' WHERE iso_code_a3 = 'MLT';
--;;
UPDATE country SET iso_code_a2 = 'CA' WHERE iso_code_a3 = 'CAN';
--;;
UPDATE country SET iso_code_a2 = 'PK' WHERE iso_code_a3 = 'PAK';
--;;
UPDATE country SET iso_code_a2 = 'VU' WHERE iso_code_a3 = 'VUT';
--;;
UPDATE country SET iso_code_a2 = 'KH' WHERE iso_code_a3 = 'KHM';
--;;
UPDATE country SET iso_code_a2 = 'ER' WHERE iso_code_a3 = 'ERI';
--;;
UPDATE country SET iso_code_a2 = 'ME' WHERE iso_code_a3 = 'MNE';
--;;
UPDATE country SET iso_code_a2 = 'FR' WHERE iso_code_a3 = 'FRA';
--;;
UPDATE country SET iso_code_a2 = 'CM' WHERE iso_code_a3 = 'CMR';
--;;
UPDATE country SET iso_code_a2 = 'SX' WHERE iso_code_a3 = 'SXM';
--;;
UPDATE country SET iso_code_a2 = 'SD' WHERE iso_code_a3 = 'SDN';
--;;
UPDATE country SET iso_code_a2 = 'CU' WHERE iso_code_a3 = 'CUB';
--;;
UPDATE country SET iso_code_a2 = 'TH' WHERE iso_code_a3 = 'THA';
--;;
UPDATE country SET iso_code_a2 = 'UY' WHERE iso_code_a3 = 'URY';
--;;
UPDATE country SET iso_code_a2 = 'CK' WHERE iso_code_a3 = 'COK';
--;;
UPDATE country SET iso_code_a2 = 'IO' WHERE iso_code_a3 = 'IOT';
--;;
UPDATE country SET iso_code_a2 = 'AZ' WHERE iso_code_a3 = 'AZE';
--;;
UPDATE country SET iso_code_a2 = 'VA' WHERE iso_code_a3 = 'VAT';
--;;
UPDATE country SET iso_code_a2 = 'CW' WHERE iso_code_a3 = 'CUW';
--;;
UPDATE country SET iso_code_a2 = 'TD' WHERE iso_code_a3 = 'TCD';
--;;
UPDATE country SET iso_code_a2 = 'KM' WHERE iso_code_a3 = 'COM';
--;;
UPDATE country SET iso_code_a2 = 'BL' WHERE iso_code_a3 = 'BLM';
--;;
UPDATE country SET iso_code_a2 = 'BW' WHERE iso_code_a3 = 'BWA';
--;;
UPDATE country SET iso_code_a2 = 'NR' WHERE iso_code_a3 = 'NRU';
--;;
UPDATE country SET iso_code_a2 = 'BS' WHERE iso_code_a3 = 'BHS';
--;;
UPDATE country SET iso_code_a2 = 'AD' WHERE iso_code_a3 = 'AND';
--;;
UPDATE country SET iso_code_a2 = 'GI' WHERE iso_code_a3 = 'GIB';
--;;
UPDATE country SET iso_code_a2 = 'BB' WHERE iso_code_a3 = 'BRB';
--;;
UPDATE country SET iso_code_a2 = 'TJ' WHERE iso_code_a3 = 'TJK';
--;;
UPDATE country SET iso_code_a2 = 'BI' WHERE iso_code_a3 = 'BDI';
--;;
UPDATE country SET iso_code_a2 = 'IM' WHERE iso_code_a3 = 'IMN';
--;;
UPDATE country SET iso_code_a2 = 'PS' WHERE iso_code_a3 = 'PSE';
--;;
UPDATE country SET iso_code_a2 = 'EE' WHERE iso_code_a3 = 'EST';
--;;
UPDATE country SET iso_code_a2 = 'BT' WHERE iso_code_a3 = 'BTN';
--;;
UPDATE country SET iso_code_a2 = 'KI' WHERE iso_code_a3 = 'KIR';
--;;
UPDATE country SET iso_code_a2 = 'KR' WHERE iso_code_a3 = 'KOR';
--;;
UPDATE country SET iso_code_a2 = 'SB' WHERE iso_code_a3 = 'SLB';
--;;
UPDATE country SET iso_code_a2 = 'KZ' WHERE iso_code_a3 = 'KAZ';
--;;
UPDATE country SET iso_code_a2 = 'AW' WHERE iso_code_a3 = 'ABW';
--;;
UPDATE country SET iso_code_a2 = 'JE' WHERE iso_code_a3 = 'JEY';
--;;
UPDATE country SET iso_code_a2 = 'SZ' WHERE iso_code_a3 = 'SWZ';
--;;
UPDATE country SET iso_code_a2 = 'IT' WHERE iso_code_a3 = 'ITA';
--;;
UPDATE country SET iso_code_a2 = 'NA' WHERE iso_code_a3 = 'NAM';
--;;
UPDATE country SET iso_code_a2 = 'PH' WHERE iso_code_a3 = 'PHL';
--;;
UPDATE country SET iso_code_a2 = 'RU' WHERE iso_code_a3 = 'RUS';
--;;
UPDATE country SET iso_code_a2 = 'MM' WHERE iso_code_a3 = 'MMR';
--;;
UPDATE country SET iso_code_a2 = 'VI' WHERE iso_code_a3 = 'VIR';
--;;
UPDATE country SET iso_code_a2 = 'KN' WHERE iso_code_a3 = 'KNA';
--;;
UPDATE country SET iso_code_a2 = 'NL' WHERE iso_code_a3 = 'NLD';
--;;
UPDATE country SET iso_code_a2 = 'LS' WHERE iso_code_a3 = 'LSO';
--;;
UPDATE country SET iso_code_a2 = 'HN' WHERE iso_code_a3 = 'HND';
--;;
UPDATE country SET iso_code_a2 = 'MX' WHERE iso_code_a3 = 'MEX';
--;;
UPDATE country SET iso_code_a2 = 'CF' WHERE iso_code_a3 = 'CAF';
--;;
UPDATE country SET iso_code_a2 = 'AX' WHERE iso_code_a3 = 'ALA';
--;;
UPDATE country SET iso_code_a2 = 'ET' WHERE iso_code_a3 = 'ETH';
--;;
UPDATE country SET iso_code_a2 = 'DK' WHERE iso_code_a3 = 'DNK';
--;;
UPDATE country SET iso_code_a2 = 'KW' WHERE iso_code_a3 = 'KWT';
--;;
UPDATE country SET iso_code_a2 = 'DM' WHERE iso_code_a3 = 'DMA';
--;;
UPDATE country SET iso_code_a2 = 'EC' WHERE iso_code_a3 = 'ECU';
--;;
UPDATE country SET iso_code_a2 = 'RW' WHERE iso_code_a3 = 'RWA';
--;;
UPDATE country SET iso_code_a2 = 'SJ' WHERE iso_code_a3 = 'SJM';
--;;
UPDATE country SET iso_code_a2 = 'AG' WHERE iso_code_a3 = 'ATG';
--;;
UPDATE country SET iso_code_a2 = 'TL' WHERE iso_code_a3 = 'TLS';
--;;
UPDATE country SET iso_code_a2 = 'NE' WHERE iso_code_a3 = 'NER';
--;;
UPDATE country SET iso_code_a2 = 'GR' WHERE iso_code_a3 = 'GRC';
--;;
UPDATE country SET iso_code_a2 = 'SO' WHERE iso_code_a3 = 'SOM';
--;;
UPDATE country SET iso_code_a2 = 'TO' WHERE iso_code_a3 = 'TON';
--;;
UPDATE country SET iso_code_a2 = 'GW' WHERE iso_code_a3 = 'GNB';
--;;
UPDATE country SET iso_code_a2 = 'GD' WHERE iso_code_a3 = 'GRD';
--;;
UPDATE country SET iso_code_a2 = 'GE' WHERE iso_code_a3 = 'GEO';
--;;
UPDATE country SET iso_code_a2 = 'SV' WHERE iso_code_a3 = 'SLV';
--;;
UPDATE country SET iso_code_a2 = 'LU' WHERE iso_code_a3 = 'LUX';
--;;
UPDATE country SET iso_code_a2 = 'NC' WHERE iso_code_a3 = 'NCL';
--;;
UPDATE country SET iso_code_a2 = 'IS' WHERE iso_code_a3 = 'ISL';
--;;
UPDATE country SET iso_code_a2 = 'QA' WHERE iso_code_a3 = 'QAT';
--;;
UPDATE country SET iso_code_a2 = 'BR' WHERE iso_code_a3 = 'BRA';
--;;
UPDATE country SET iso_code_a2 = 'BA' WHERE iso_code_a3 = 'BIH';
--;;
UPDATE country SET iso_code_a2 = 'NZ' WHERE iso_code_a3 = 'NZL';
--;;
UPDATE country SET iso_code_a2 = 'JP' WHERE iso_code_a3 = 'JPN';
--;;
UPDATE country SET iso_code_a2 = 'PE' WHERE iso_code_a3 = 'PER';
--;;
UPDATE country SET iso_code_a2 = 'LB' WHERE iso_code_a3 = 'LBN';
--;;
UPDATE country SET iso_code_a2 = 'BH' WHERE iso_code_a3 = 'BHR';
--;;
UPDATE country SET iso_code_a2 = 'AQ' WHERE iso_code_a3 = 'ATA';
--;;
UPDATE country SET iso_code_a2 = 'TR' WHERE iso_code_a3 = 'TUR';
--;;
UPDATE country SET iso_code_a2 = 'VE' WHERE iso_code_a3 = 'VEN';
--;;
UPDATE country SET iso_code_a2 = 'TT' WHERE iso_code_a3 = 'TTO';
--;;
UPDATE country SET iso_code_a2 = 'ST' WHERE iso_code_a3 = 'STP';
--;;
UPDATE country SET iso_code_a2 = 'ES' WHERE iso_code_a3 = 'ESP';
--;;
UPDATE country SET iso_code_a2 = 'AI' WHERE iso_code_a3 = 'AIA';
--;;
UPDATE country SET iso_code_a2 = 'SG' WHERE iso_code_a3 = 'SGP';
--;;
UPDATE country SET iso_code_a2 = 'SN' WHERE iso_code_a3 = 'SEN';
--;;
UPDATE country SET iso_code_a2 = 'HM' WHERE iso_code_a3 = 'HMD';
--;;
UPDATE country SET iso_code_a2 = 'MG' WHERE iso_code_a3 = 'MDG';
--;;
UPDATE country SET iso_code_a2 = 'IL' WHERE iso_code_a3 = 'ISR';
--;;
UPDATE country SET iso_code_a2 = 'BQ' WHERE iso_code_a3 = 'BES';
--;;
UPDATE country SET iso_code_a2 = 'AS' WHERE iso_code_a3 = 'ASM';
--;;
UPDATE country SET iso_code_a2 = 'US' WHERE iso_code_a3 = 'USA';
--;;
UPDATE country SET iso_code_a2 = 'PW' WHERE iso_code_a3 = 'PLW';
--;;
UPDATE country SET iso_code_a2 = 'AL' WHERE iso_code_a3 = 'ALB';
--;;
UPDATE country SET iso_code_a2 = 'LR' WHERE iso_code_a3 = 'LBR';
--;;
UPDATE country SET iso_code_a2 = 'BO' WHERE iso_code_a3 = 'BOL';
--;;
UPDATE country SET iso_code_a2 = 'SS' WHERE iso_code_a3 = 'SSD';
--;;
UPDATE country SET iso_code_a2 = 'BN' WHERE iso_code_a3 = 'BRN';
--;;
UPDATE country SET iso_code_a2 = 'CL' WHERE iso_code_a3 = 'CHL';
--;;
UPDATE country SET iso_code_a2 = 'FM' WHERE iso_code_a3 = 'FSM';
--;;
UPDATE country SET iso_code_a2 = 'PA' WHERE iso_code_a3 = 'PAN';
--;;
UPDATE country SET iso_code_a2 = 'FK' WHERE iso_code_a3 = 'FLK';
--;;
UPDATE country SET iso_code_a2 = 'CD' WHERE iso_code_a3 = 'COD';
--;;
UPDATE country SET iso_code_a2 = 'MP' WHERE iso_code_a3 = 'MNP';
--;;
UPDATE country SET iso_code_a2 = 'IE' WHERE iso_code_a3 = 'IRL';
--;;
UPDATE country SET iso_code_a2 = 'CI' WHERE iso_code_a3 = 'CIV';
--;;
UPDATE country SET iso_code_a2 = 'ML' WHERE iso_code_a3 = 'MLI';
--;;
UPDATE country SET iso_code_a2 = 'MY' WHERE iso_code_a3 = 'MYS';
--;;
UPDATE country SET iso_code_a2 = 'YT' WHERE iso_code_a3 = 'MYT';
--;;
UPDATE country SET iso_code_a2 = 'PN' WHERE iso_code_a3 = 'PCN';
--;;
UPDATE country SET iso_code_a2 = 'UM' WHERE iso_code_a3 = 'UMI';
--;;
UPDATE country SET iso_code_a2 = 'CX' WHERE iso_code_a3 = 'CXR';
--;;
UPDATE country SET iso_code_a2 = 'AU' WHERE iso_code_a3 = 'AUS';
--;;
UPDATE country SET iso_code_a2 = 'BZ' WHERE iso_code_a3 = 'BLZ';
--;;
UPDATE country SET iso_code_a2 = 'UZ' WHERE iso_code_a3 = 'UZB';
--;;
UPDATE country SET iso_code_a2 = 'SK' WHERE iso_code_a3 = 'SVK';
--;;
UPDATE country SET iso_code_a2 = 'JM' WHERE iso_code_a3 = 'JAM';
--;;
UPDATE country SET iso_code_a2 = 'NI' WHERE iso_code_a3 = 'NIC';
--;;
UPDATE country SET iso_code_a2 = 'TZ' WHERE iso_code_a3 = 'TZA';
--;;
UPDATE country SET iso_code_a2 = 'CO' WHERE iso_code_a3 = 'COL';
--;;
UPDATE country SET iso_code_a2 = 'NG' WHERE iso_code_a3 = 'NGA';
--;;
UPDATE country SET iso_code_a2 = 'PY' WHERE iso_code_a3 = 'PRY';
--;;
UPDATE country SET iso_code_a2 = 'GU' WHERE iso_code_a3 = 'GUM';
--;;
UPDATE country SET iso_code_a2 = 'KE' WHERE iso_code_a3 = 'KEN';
--;;
UPDATE country SET iso_code_a2 = 'GN' WHERE iso_code_a3 = 'GIN';
--;;
UPDATE country SET iso_code_a2 = 'HK' WHERE iso_code_a3 = 'HKG';
--;;
UPDATE country SET iso_code_a2 = 'CH' WHERE iso_code_a3 = 'CHE';
--;;
UPDATE country SET iso_code_a2 = 'LI' WHERE iso_code_a3 = 'LIE';
--;;
UPDATE country SET iso_code_a2 = 'KP' WHERE iso_code_a3 = 'PRK';
--;;
UPDATE country SET iso_code_a2 = 'DZ' WHERE iso_code_a3 = 'DZA';
--;;
UPDATE country SET iso_code_a2 = 'LA' WHERE iso_code_a3 = 'LAO';
--;;
UPDATE country SET iso_code_a2 = 'MU' WHERE iso_code_a3 = 'MUS';
--;;
UPDATE country SET iso_code_a2 = 'NO' WHERE iso_code_a3 = 'NOR';
--;;
UPDATE country SET iso_code_a2 = 'GL' WHERE iso_code_a3 = 'GRL';
--;;
UPDATE country SET iso_code_a2 = 'GA' WHERE iso_code_a3 = 'GAB';
--;;
UPDATE country SET iso_code_a2 = ltrim(iso_code_a3,'x') WHERE iso_code_a2 IS NULL;
--;;
UPDATE country SET iso_code_a2 = 'xx' WHERE iso_code_a3 = 'xxx';
--;;
COMMIT;
