DROP TABLE IF EXISTS technology_like CASCADE;
DROP TABLE IF EXISTS resource_like CASCADE;
DROP TABLE IF EXISTS event_like CASCADE;
DROP TABLE IF EXISTS policy_like CASCADE;
DROP TABLE IF EXISTS initiative_like CASCADE;
DROP TABLE IF EXISTS case_study_like CASCADE;
DROP TABLE IF EXISTS organisation_like CASCADE;
