-- :name get-topics :? :*
-- :doc Gets the list of topics. If count-only? parameter is set to true, the query will only group and count the topics.
-- :require [gpml.db.topic]
--~ (#'gpml.db.topic/generate-topic-query params)
,
cte_results AS (
--~ (#'gpml.db.topic/generate-filter-topic-snippet params)
)
--~ (#'gpml.db.topic/generate-get-topics params)

-- :name get-flat-topics
-- :doc Get a flat list of all topics
WITH flat_topic AS (
  SELECT
    REPLACE(LOWER(r.type), ' ', '_') AS topic,
    r.id,
    0 AS version,
    NULL::json AS submitting_as,
    r.title,
    NULL AS original_title,
    NULL AS data_source,
    r.publish_year,
    NULL AS start_date,
    NULL AS end_date,
    r.summary,
    value,
    r.image,
    NULL AS logo,
    r.geo_coverage_type::text,
    r.attachments,
    r.remarks,
    r.created,
    r.modified,
    r.country::text,
    NULL AS city,
    NULL AS type_of_law,
    NULL AS organisation_type,
    NULL AS development_stage,
    NULL::boolean AS specifications_provided,
    NULL AS email,
    r.valid_from,
    r.valid_to,
    NULL::int AS implementing_mea,
    r.reviewed_at,
    r.reviewed_by,
    r.review_status,
    r.value_remarks,
    r.value_currency,
    r.created_by,
    r.url,
    NULL AS repeals,
    r.info_docs,
    r.sub_content_type,
    r.capacity_building,
    NULL AS event_type,
    NULL AS recording,
    array_remove(array_agg(rc.related_resource_id), NULL) AS related_content,
    NULL::text[] AS topics,
    NULL AS record_number,
    r.first_publication_date::text,
    r.latest_amendment_date::text,
    NULL AS status,
    r.subnational_city,
    NULL AS headquarter,
    r.language,
    r.document_preview,
    NULL AS reporting_to,
    NULL AS sdg_initiative,
    NULL AS q4,
    NULL AS q4_1_1,
    NULL AS q4_1_2,
    NULL AS q4_2_1,
    NULL AS q4_3_1,
    NULL AS q4_4_1,
    NULL AS q4_4_3,
    NULL AS q4_4_4,
    NULL AS q4_4_5,
    NULL AS q5,
    NULL AS q7_1_1,
    NULL AS q7_1_2,
    NULL AS q7_2,
    NULL AS q8,
    NULL AS q9,
    NULL AS q10,
    NULL AS q11,
    NULL AS q12,
    NULL AS q13,
    NULL AS q14,
    NULL AS q15,
    NULL AS q16,
    NULL AS q17,
    NULL AS q18,
    NULL AS q19,
    NULL AS q20,
    NULL AS q21,
    NULL AS q26,
    NULL AS q27,
    NULL AS q28,
    NULL AS q29,
    NULL AS q30,
    NULL AS q31,
    NULL AS q32,
    NULL AS q33,
    NULL AS q34,
    NULL AS q35,
    NULL AS q36,
    NULL AS q36_1,
    NULL AS q37,
    NULL AS q37_1,
    NULL AS q38,
    NULL AS q39,
    NULL AS q40,
    NULL AS q41,
    NULL AS q41_1,
    NULL AS q1_1,
    NULL AS q35_1,
    NULL AS q1_1_1,
    array_to_string(array_remove(array_agg(o.name), NULL), ', ') AS entity_connections,
    r.image_id,
    jsonb_agg(DISTINCT jsonb_build_object('id', f.id, 'object-key', f.object_key, 'visibility', f.visibility)) FILTER (WHERE f.id IS NOT NULL) AS files
  FROM resource r
  LEFT JOIN related_content rc ON r.id = rc.resource_id AND resource_table_name = 'resource'::regclass
  LEFT JOIN organisation_resource oe ON oe.resource = r.id
  LEFT JOIN organisation o ON o.id = oe.organisation
  LEFT JOIN file f ON r.image_id = f.id
  --~ (when (:review-status params) "WHERE r.review_status = (:v:review-status)::review_status")
  GROUP BY r.id
UNION ALL
	SELECT
		'event'::text AS topic,
    e.id,
    0 AS version,
    NULL::json AS submitting_as,
    e.title,
    NULL AS original_title,
    NULL AS data_source,
    NULL AS publish_year,
    e.start_date,
    e.end_date,
    e.description AS summary,
    NULL AS value,
    e.image,
    NULL AS logo,
    e.geo_coverage_type::text,
    NULL AS attachments,
    e.remarks,
    e.created,
    e.modified,
    e.country::text,
    e.city,
    NULL AS type_of_law,
    NULL AS organisation_type,
    NULL AS development_stage,
    NULL::boolean AS specifications_provided,
    NULL AS email,
    NULL AS valid_from,
    NULL AS valid_to,
    NULL::int AS implementing_mea,
    e.reviewed_at,
    e.reviewed_by,
    e.review_status,
    NULL AS value_remarks,
    NULL AS value_currency,
    e.created_by,
    e.url,
    NULL AS repeals,
    e.info_docs,
    e.sub_content_type,
    e.capacity_building,
    e.event_type,
    e.recording,
    array_remove(array_agg(rc.related_resource_id), NULL) AS related_content,
    NULL::text[] AS topics,
    NULL AS record_number,
    NULL AS first_publication_date,
    NULL AS latest_amendment_date,
    NULL AS status,
    e.subnational_city,
    NULL AS headquarter,
    e.language,
    e.document_preview,
    NULL AS reporting_to,
    NULL AS sdg_initiative,
    NULL AS q4,
    NULL AS q4_1_1,
    NULL AS q4_1_2,
    NULL AS q4_2_1,
    NULL AS q4_3_1,
    NULL AS q4_4_1,
    NULL AS q4_4_3,
    NULL AS q4_4_4,
    NULL AS q4_4_5,
    NULL AS q5,
    NULL AS q7_1_1,
    NULL AS q7_1_2,
    NULL AS q7_2,
    NULL AS q8,
    NULL AS q9,
    NULL AS q10,
    NULL AS q11,
    NULL AS q12,
    NULL AS q13,
    NULL AS q14,
    NULL AS q15,
    NULL AS q16,
    NULL AS q17,
    NULL AS q18,
    NULL AS q19,
    NULL AS q20,
    NULL AS q21,
    NULL AS q26,
    NULL AS q27,
    NULL AS q28,
    NULL AS q29,
    NULL AS q30,
    NULL AS q31,
    NULL AS q32,
    NULL AS q33,
    NULL AS q34,
    NULL AS q35,
    NULL AS q36,
    NULL AS q36_1,
    NULL AS q37,
    NULL AS q37_1,
    NULL AS q38,
    NULL AS q39,
    NULL AS q40,
    NULL AS q41,
    NULL AS q41_1,
    NULL AS q1_1,
    NULL AS q35_1,
    NULL AS q1_1_1,
    array_to_string(array_remove(array_agg(o.name), NULL), ', ') AS entity_connections,
    e.image_id,
    jsonb_agg(DISTINCT jsonb_build_object('id', f.id, 'object-key', f.object_key, 'visibility', f.visibility)) FILTER (WHERE f.id IS NOT NULL) AS files
    FROM event e
    LEFT JOIN related_content rc ON e.id = rc.resource_id AND resource_table_name = 'event'::regclass
    LEFT JOIN organisation_event oe ON oe.event = e.id
    LEFT JOIN organisation o ON o.id = oe.organisation
    LEFT JOIN file f ON e.image_id = f.id
    --~ (when (:review-status params) "WHERE e.review_status = (:v:review-status)::review_status")
    GROUP BY e.id
UNION ALL
	SELECT
		'initiative'::text AS topic,
    i.id,
    i.version,
    i.q1::json->'1-0' AS submitting_as,
    i.q2::text AS title,
    NULL AS original_title,
    NULL AS data_source,
    NULL AS publish_year,
    NULL AS start_date,
    NULL AS end_date,
    i.q3::text AS summary,
    NULL AS value,
    i.qimage AS image,
    NULL AS logo,
    i.geo_coverage_type::text,
    NULL AS attachments,
    NULL AS remarks,
    i.created,
    i.modified,
    NULL AS country,
    NULL AS city,
    NULL AS type_of_law,
    NULL AS organisation_type,
    NULL AS development_stage,
    NULL::boolean AS specifications_provided,
    NULL AS email,
    NULL AS valid_from,
    NULL AS valid_to,
    NULL::int AS implementing_mea,
    i.reviewed_at,
    i.reviewed_by,
    i.review_status,
    NULL AS value_remarks,
    NULL AS value_currency,
    i.created_by,
    i.url,
    NULL AS repeals,
    i.info_docs,
    i.sub_content_type,
    NULL AS capacity_building,
    NULL AS event_type,
    NULL AS recording,
    array_remove(array_agg(rc.related_resource_id), NULL) AS related_content,
    NULL::text[] AS topics,
    NULL AS record_number,
    NULL AS first_publication_date,
    NULL AS latest_amendment_date,
    NULL AS status,
    NULL AS subnational_city,
    NULL AS headquarter,
    i.language,
    i.document_preview,
    i.q7::text AS reporting_to,
    i.q7_1_0::text AS sdg_initiative,
    i.q4::text,
    i.q4_1_1::text,
    i.q4_1_2::text,
    i.q4_2_1::text,
    i.q4_3_1::text,
    i.q4_4_1::text,
    i.q4_4_3::text,
    i.q4_4_4::text,
    i.q4_4_5::text,
    i.q5::text,
    i.q7_1_1::text,
    i.q7_1_2::text,
    i.q7_2::text,
    i.q8::text,
    i.q9::text,
    i.q10::text,
    i.q11::text,
    i.q12::text,
    i.q13::text,
    i.q14::text,
    i.q15::text,
    i.q16::text,
    i.q17::text,
    i.q18::text,
    i.q19::text,
    i.q20::text,
    i.q21::text,
    i.q26::text,
    i.q27::text,
    i.q28::text,
    i.q29::text,
    i.q30::text,
    i.q31::text,
    i.q32::text,
    i.q33::text,
    i.q34::text,
    i.q35::text,
    i.q36::text,
    i.q36_1::text,
    i.q37::text,
    i.q37_1::text,
    i.q38::text,
    i.q39::text,
    i.q40::text,
    i.q41::text,
    i.q41_1::text,
    i.q1_1::text,
    i.q35_1::text,
    i.q1_1_1::text,
    array_to_string(array_remove(array_agg(o.name), NULL), ', ') AS entity_connections,
    i.image_id,
    jsonb_agg(DISTINCT jsonb_build_object('id', f.id, 'object-key', f.object_key, 'visibility', f.visibility)) FILTER (WHERE f.id IS NOT NULL) AS files
    FROM initiative i
    LEFT JOIN related_content rc ON i.id = rc.resource_id AND resource_table_name = 'initiative'::regclass
    LEFT JOIN organisation_initiative oe ON oe.initiative = i.id
    LEFT JOIN organisation o ON o.id = oe.organisation
    LEFT JOIN file f ON i.image_id = f.id
	--~ (when (:review-status params) "WHERE i.review_status = (:v:review-status)::review_status")
  GROUP BY i.id
UNION ALL
  SELECT
	'policy'::text AS topic,
    p.id,
    0 AS version,
    NULL::json AS submitting_as,
    p.title,
    p.original_title,
    p.data_source,
    NULL AS publish_year,
    NULL AS start_date,
    NULL AS end_date,
    p.abstract AS summary,
    NULL AS value,
    p.image,
    NULL AS logo,
    p.geo_coverage_type::text,
    p.attachments,
    p.remarks,
    p.created,
    p.modified,
    p.country::text,
    NULL AS city,
    p.type_of_law,
    NULL AS organisation_type,
    NULL AS development_stage,
    NULL::boolean AS specifications_provided,
    NULL AS email,
    NULL AS valid_from,
    NULL AS valid_to,
    p.implementing_mea,
    p.reviewed_at,
    p.reviewed_by,
    p.review_status,
    NULL AS value_remarks,
    NULL AS value_currency,
    p.created_by,
    p.url,
    p.repeals,
    p.info_docs,
    p.sub_content_type,
    NULL AS capacity_building,
    NULL AS event_type,
    NULL AS recording,
    array_remove(array_agg(rc.related_resource_id), NULL) AS related_content,
    p.topics,
    p.record_number,
    p.first_publication_date::text,
    p.latest_amendment_date::text,
    p.status,
    p.subnational_city,
    NULL AS headquarter,
    p.language,
    p.document_preview,
		NULL AS reporting_to,
		NULL AS sdg_initiative,
    NULL AS q4,
    NULL AS q4_1_1,
    NULL AS q4_1_2,
    NULL AS q4_2_1,
    NULL AS q4_3_1,
    NULL AS q4_4_1,
    NULL AS q4_4_3,
    NULL AS q4_4_4,
    NULL AS q4_4_5,
    NULL AS q5,
    NULL AS q7_1_1,
    NULL AS q7_1_2,
    NULL AS q7_2,
    NULL AS q8,
    NULL AS q9,
    NULL AS q10,
    NULL AS q11,
    NULL AS q12,
    NULL AS q13,
    NULL AS q14,
    NULL AS q15,
    NULL AS q16,
    NULL AS q17,
    NULL AS q18,
    NULL AS q19,
    NULL AS q20,
    NULL AS q21,
    NULL AS q26,
    NULL AS q27,
    NULL AS q28,
    NULL AS q29,
    NULL AS q30,
    NULL AS q31,
    NULL AS q32,
    NULL AS q33,
    NULL AS q34,
    NULL AS q35,
    NULL AS q36,
    NULL AS q36_1,
    NULL AS q37,
    NULL AS q37_1,
    NULL AS q38,
    NULL AS q39,
    NULL AS q40,
    NULL AS q41,
    NULL AS q41_1,
    NULL AS q1_1,
    NULL AS q35_1,
    NULL AS q1_1_1,
    array_to_string(array_remove(array_agg(o.name), NULL), ', ') AS entity_connections,
    p.image_id,
    jsonb_agg(DISTINCT jsonb_build_object('id', f.id, 'object-key', f.object_key, 'visibility', f.visibility)) FILTER (WHERE f.id IS NOT NULL) AS files
  FROM policy p
  LEFT JOIN related_content rc ON p.id = rc.resource_id AND resource_table_name = 'policy'::regclass
  LEFT JOIN organisation_policy oe ON oe.policy = p.id
  LEFT JOIN organisation o ON o.id = oe.organisation
  LEFT JOIN file f ON p.image_id = f.id
  --~ (when (:review-status params) "WHERE p.review_status = (:v:review-status)::review_status")
  GROUP BY p.id
UNION ALL
  SELECT
    'technology'::text AS topic,
    t.id,
    0 AS version,
    NULL::json AS submitting_as,
    t.name AS title,
    NULL AS original_title,
    NULL AS data_source,
    t.year_founded AS publish_year,
    NULL AS start_date,
    NULL AS end_date,
    t.remarks AS summary,
    NULL AS value,
    t.image,
    t.logo,
    t.geo_coverage_type::text,
    t.attachments,
    t.remarks,
    t.created,
    t.modified,
    t.country::text,
    NULL AS city,
    NULL AS type_of_law,
    t.organisation_type,
    t.development_stage,
    t.specifications_provided,
    t.email,
    NULL AS valid_from,
    NULL AS valid_to,
		NULL::int AS implementing_mea,
    t.reviewed_at,
    t.reviewed_by,
    t.review_status,
    NULL AS value_remarks,
    NULL AS value_currency,
    t.created_by,
    t.url,
    NULL AS repeals,
    t.info_docs,
    t.sub_content_type,
    NULL AS capacity_building,
    NULL AS event_type,
    NULL AS recording,
    array_remove(array_agg(rc.related_resource_id), NULL) AS related_content,
    NULL::text[] AS topics,
    NULL AS record_number,
    NULL AS first_publication_date,
    NULL AS latest_amendment_date,
    NULL AS status,
    t.subnational_city,
    t.headquarter,
    t.language,
    t.document_preview,
		NULL AS reporting_to,
		NULL AS sdg_initiative,
    NULL AS q4,
    NULL AS q4_1_1,
    NULL AS q4_1_2,
    NULL AS q4_2_1,
    NULL AS q4_3_1,
    NULL AS q4_4_1,
    NULL AS q4_4_3,
    NULL AS q4_4_4,
    NULL AS q4_4_5,
    NULL AS q5,
    NULL AS q7_1_1,
    NULL AS q7_1_2,
    NULL AS q7_2,
    NULL AS q8,
    NULL AS q9,
    NULL AS q10,
    NULL AS q11,
    NULL AS q12,
    NULL AS q13,
    NULL AS q14,
    NULL AS q15,
    NULL AS q16,
    NULL AS q17,
    NULL AS q18,
    NULL AS q19,
    NULL AS q20,
    NULL AS q21,
    NULL AS q26,
    NULL AS q27,
    NULL AS q28,
    NULL AS q29,
    NULL AS q30,
    NULL AS q31,
    NULL AS q32,
    NULL AS q33,
    NULL AS q34,
    NULL AS q35,
    NULL AS q36,
    NULL AS q36_1,
    NULL AS q37,
    NULL AS q37_1,
    NULL AS q38,
    NULL AS q39,
    NULL AS q40,
    NULL AS q41,
    NULL AS q41_1,
    NULL AS q1_1,
    NULL AS q35_1,
    NULL AS q1_1_1,
    array_to_string(array_remove(array_agg(o.name), NULL), ', ') AS entity_connections,
    t.image_id,
    jsonb_agg(DISTINCT jsonb_build_object('id', f.id, 'object-key', f.object_key, 'visibility', f.visibility)) FILTER (WHERE f.id IS NOT NULL) AS files
  FROM technology t
  LEFT JOIN related_content rc ON t.id = rc.resource_id AND resource_table_name = 'technology'::regclass
  LEFT JOIN organisation_technology oe ON oe.technology = t.id
  LEFT JOIN organisation o ON o.id = oe.organisation
  LEFT JOIN file f ON t.image_id = f.id
  --~ (when (:review-status params) "WHERE t.review_status = (:v:review-status)::review_status")
  GROUP BY t.id
)
SELECT * FROM flat_topic ORDER BY id;
